### ISSUE TITLE
control redraw numbers when using mousemove

### ISSUE THREAD

**Issue by priestoferis** [konvajs/vue-konva#101]
I'm trying to solve a problem, where using `mousemove` on a shape results in the animation freezing a lot. It seems similar to this problem: https://konvajs.org/docs/performance/Batch_Draw.html, but I do not see how `batchDraw` could be used with vue-konva, since redraws seem to be triggered anyway.

Here's a working example of what I want to solve: https://codesandbox.io/s/vue-konva-mousemove-performance-bsci3 (working in the sense that it does what I want, but it is not a smooth animation).

How can one get around this?

**Comment by lavrton** [comment]
`vue-konva` is using `batchDraw` in its internals.

But as I can see in your demo, you are not using `vue` methods to update components props, instead, you change them directly:

```
this.$refs.rect.getStage().to({
        width: x_ - this.origo_pos_x,
        height: y_ - this.origo_pos_y,
        duration: 0
});
```

It can work ok for many cases and can be faster than using `vue` props. BTW, if you have `duration: 0` you probably just want to use `setAttrs(attrs)` method.

Also, I see that the demo is not "freezing", it works smoothly for me, it just not trigger `mousemove` as you expect. The event is not triggered when you inside the blue rect.

Updated demo: https://codesandbox.io/s/vue-konva-mousemove-performance-zofq6

**Comment by priestoferis** [comment]
Thanks, I see I haven't noticed that's the issue, thanks!
