### ISSUE TITLE
Implementing Transformer within 'setup'

### ISSUE THREAD

**Issue by algebrot** [konvajs/vue-konva#102]
Hello, I am following your [Transformer tutorial](https://konvajs.org/docs/vue/Transformer.html) and would appreciate advice on the approach I am taking. 

I am working in a createComponent method with a 'name:' and 'setup:' like:
`export default createComponent({ name: ... , setup: () => { ... }, });`

In the setup I am creating const mouse events like:
`const onMouseDown = (event: KonvaPointerEvent) => { ... };`

I am also trying to implement handleTransformEnd and updateTransformer in this way instead of putting them outside of my setup in 'methods:' like:
`const handleTransformEnd = (event: KonvaPointerEvent) => { ... };`
`const updateTransformer = computed(() => { ... });`

However, I'm having issues with finding the transformer with the line:
`const transformerNode = $refs.transformer.getNode();` 

(I got rid of `this` since it is in the setup) The name `$refs` is not recognized and neither is `transformer` when I simplify the line like:
`const transformerNode = transformer.getNode();` 

Is this because I am implementing this within setup and not using a separate methods implementation like you do? I appreciate your feedback!

**Comment by lavrton** [comment]
Sorry, I have no idea what that setup installation means.

In the demo, I am accessing vue references. I guess you should do something similar.
