### ISSUE TITLE
Question: What is the best way to implement stack behavior?

### ISSUE THREAD

**Issue by agoretsky** [konvajs/vue-konva#103]
I'm trying to implement a stack component:

Stack.vue:
```
<template>
  <v-group ref="stackRoot">
    <slot />
  </v-group>
</template>

<script>
export default {
  mounted() {
    let root = this.$refs.stackRoot.getNode();
    let y = 0;
    Array.from(root.children).forEach((node, index) => {
      if (index !== 0) {
        y += 10;
      }

      node.y(y);
      let height = node.getClientRect().height;
      y += height;
    });
  }
};
</script>
```

And use it like this:
```
      <stack ref="content">
        <v-text ref="text" :config="textConfig" />
        <stack ref="buttonStack">
          <btn text="Button 1" />
          <btn text="Button 2" />
          <btn text="Button 3" />
          <btn text="Button 4" />
        </stack>
      </stack>
```

Now if the height of one of the stack children will be changed later - it won't work. To make it work I should find a way to detect height changes, so I tried to use event heightChange.
 
But heightChange won't fire on text shape when text changed and it won't fire on wraped node.

Any idea what would be the best way to implement a stack that will automatically adjust when children size changes?

Thanks

**Comment by lavrton** [comment]
It may be not simple to detect children's height change. You may try to listen to `height` and other attrs changes (such as `textChange`).

But probably it will be simpler if a child can report back into parent component its height, so the parent can recalculate positions.

```
<stack ref="content">
        <v-text ref="text" :config="textConfig" />
        <stack ref="buttonStack">
          <btn text="Button 1" onHeightChange="childHeightChange" y="" />
          <btn text="Button 2" onHeightChange="childHeightChange" y=""/>
          <btn text="Button 3" onHeightChange="childHeightChange" y=""/>
          <btn text="Button 4" onHeightChange="childHeightChange" y=""/>
        </stack>
</stack>



onHeightChage(childHeight, index) {
   // recalculate positions of children
}
```

**Comment by agoretsky** [comment]
@lavrton Thanks. Implemented through firing custom Konva event with bubbling enabled in child and listening on parent.
