### ISSUE TITLE
Drawing click Polygons

### ISSUE THREAD

**Issue by WhatWhatz** [konvajs/vue-konva#104]
Is the `v-polygon` supposed to create a polygon that are defined each time I click? if not how can I draw polygons that are afterwards editable?

**Comment by lavrton** [comment]
What did you try?

1. you can draw polygon (probably with the line)
2. You can draw circles on polygon corners
3. You can change polygon points when circles are dragged

**Comment by WhatWhatz** [comment]
So I was able to draw polygons with the `v-line`. I need the same behaviour as a transformer but for polygons. Therefore I am trying to create a transformer so here what I did (all functions are under methods of Vue ): 
function 1: creates circles in poly break points
``` 
 polyTransformer() {
      console.log('creating')
      let stage = this.$refs.stage.getNode()
      const selectedPoly = stage.findOne('.' + this.selectedShapeName)
      let points = selectedPoly.points()
      let anchor
      for (let i = 0; i <= points.length - 2; i = i + 2) {
        anchor = new Konva.Circle({
          x: points[i],
          y: points[i + 1],
          radius: 5,
          fill: 'white',
          stroke: 'black',
          draggable: true
        })
        this.anchors.push(anchor)
        this.$refs.layer.getNode().add(anchor)
        anchor.on('dragmove', () => this.updatePoly(selectedPoly))
      }
      selectedPoly.on('dragmove', () => this.updateAnchors())
    },
```
function 2: updates the poly if a circle is moved
```
    updatePoly(poly) {
      console.log('moving')
      let points = []
      for (let i = 0; i < this.anchors.length; i++) {
        points = [...points, this.anchors[i].x(), this.anchors[i].y()]
        poly.points(points)
        this.$refs.layer.getNode().batchDraw()
      }
    },
```
function 3:  delete the transformer if not selected
```
    polyTransformerDetach() {
      if (this.anchors.length) {
        console.log('destroying')

        for (let i = 0; i < this.anchors.length; i++) {
          this.anchors[i].destroy()
        }
        this.anchors = []
        this.$refs.layer.getNode().batchDraw()
      }
    },
```
function 4 : move anchors if poly is dragged
```
    updateAnchors() {
      console.log('updating')
      let stage = this.$refs.stage.getNode()
      const selectedPoly = stage.findOne('.' + this.selectedShapeName)
      let points = selectedPoly.points()
      let j = 0

      for (let i = 0; i < this.anchors.length; i++) {
        console.log(this.anchors[i].x())
        this.anchors[i].x(points[j])
        this.anchors[i].y(points[j + 1])
        j = j + 2
      }

      this.$refs.layer.getNode().batchDraw()
    }
```
My problem is when dragging the polygon (=function 4) anchors gets randomly added usually at (0, 0) even though I never added them and the anchors do not update to the new x,y of the points.
Is there any way to make everything move together when the object is dragged? Is there a better solution to create a transformer for polygons?

**Comment by lavrton** [comment]
The solutions is almost good.

You just need to understand that when a polygon is dragged its `points` attribute states THE SAME. While dragging the `{x, y}` is changing. So you need to take into accound that a polygon can have `x` and `y`. Not just `points`.

**Comment by WhatWhatz** [comment]
> The solutions is almost good.
> 
> You just need to understand that when a polygon is dragged its `points` attribute states THE SAME. While dragging the `{x, y}` is changing. So you need to take into accound that a polygon can have `x` and `y`. Not just `points`.

thanks alot for the hint I made it work now !

**Comment by robertsLando** [comment]
@WhatWhatz Any luck to post full code example or even better a https://codesandbox.io/ link?
