### ISSUE TITLE
Canvas area exceeds the maximum limit (width * height > 16777216) in IOS 8 Plus

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [konvajs/vue-konva#105]
Do we have a configuration solution when encountering this warning in an IOS 8 Plus Safari? **Canvas area exceeds the maximum limit (width * height > 16777216).**

Or at least a way configure a callback message for the end-user when this is encountered. Because what happens is my **vue-konva** will not show any of my line points anymore.  Below is around the size of my canvas

```
height:1737
width:1177
```

I am using version: `2.1.1` .Below is my VueConva syntax

```
<v-stage :config="chartConfig">
        <v-layer>
          <v-line
            :config="{
              points: chartPoints,
              stroke: chartLineStroke,
              strokeWidth: strokeWidth
            }"
          />
        </v-layer>
</v-stage>

chartPoints:  [815, 70, 853, 100, 663, 130, 511, 160, 625, 190, 1777, 1220, 1397, 1250, 1853, 1280, 1511, 1310, 1511, 1340, 2891, 2370, 21157, 2400, 2739, 2430, 2131, 2460, 21119, 2490, 3511, 3520, 3663, 3550, 3701, 3580, 31005, 3610, 31081, 3640, 4891, 4670, 4853, 4700, 4207, 4730, 4587, 4760, 4321, 4790, 5815, 5820, 5891, 5850, 5549, 5880, 5245, 5910, 5777, 5940, 61119, 6970, 6967, 61000, 6131, 61030, 6663, 61060, 6397, 61090, 7283, 71120, 7739, 71150, 7663, 71180, 7777, 71210, 71157, 71240, 81005, 81270, 81005, 81300, 8739, 81330, 8587, 81360, 8359, 81390, 9283, 91420, 9511, 91450, 9815, 91480, 9321, 91510, 9397, 91540]
chartLineStroke: red
strokeWidth: 2
```

The chartPoints above is around 100 length of values. Also what I do not understand is "1177 * 1737" is not more than 16777216. I have checked in Safari Developer Tools via connection between my Macbook and Iphone, below is the visualization of the embedded canvas.. 

<img width="1276" alt="Screenshot 2020-05-02 at 16 15 43" src="https://user-images.githubusercontent.com/9837087/80859026-345e5c80-8c90-11ea-9df5-f0f2a68e7477.png">

The created canvas element when inspected  is below snippet:
```
<div class="konvajs-content" role="presentation" style="position: relative; width: 1177px; height: 1737px;">
    <canvas width="3531" height="5211" style="padding: 0px; margin: 0px; border: 0px; background-color: transparent; position: absolute; top: 0px; left: 0px; width: 1177px; height: 1737px; display: block; background-position: initial initial; background-repeat: initial initial;"> 
   </canvas>
</div>
```

**Comment by lavrton** [comment]
We can't control that warning.

By default, `Konva` automatically scales canvas to support HDPI devices (such as retina on iPhone).
You can read more about such behavior here: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

So actual canvas is 4x bigger than you specified in your stage size. Looks like such canvas is too large for Safari. So you can:
1. Decrease stage size, if possible. Make it as small as possible
2. Or do `Konva.pixelRatio = 1`. That option will make canvas smaller, but it will be blurred on HDPI devices
3. Use SVG for such use cases.

**Comment by Dean-Christian-Armada** [comment]
How can I do `Konva.pixelRatio = 1` for Vue-konva?

How can I use SVG for Vue-konva? I can not find an example on the document regarding the use of SVG Path

**Comment by lavrton** [comment]
> How can I do Konva.pixelRatio = 1 for Vue-konva?

In your `script` tag. Import `Konva` and apply this property.

> How can I use SVG for Vue-konva?

You can't. I suggested not to use `vue-konva` at all.

**Comment by Dean-Christian-Armada** [comment]
I got the pixelRatio working through the snippet below. But I have not tested it yet

```
import Konva from "konva";

export default {
  created() {
    Konva.pixelRatio = 1;
  },
}
```

Can `Konva.path` be used to convert canvas to SVG?

**Comment by lavrton** [comment]
You need to set `pixelRatio` BEFORE you create the stage.

```js
import Konva from "konva";
Konva.pixelRatio = 1;
```

> Can Konva.path be used to convert canvas to SVG?

I think yes. `Konva.Path` works very similar to `<path>` from SVG.

**Comment by Dean-Christian-Armada** [comment]
Ok, I will try Konva.path first. Thanks

**Comment by Dean-Christian-Armada** [comment]
I would just like to inform that SVG actually worked. Seems like Canvas is not the perfect solution if you just want to draw lines and shapes especially at scale. I hope this will helpful for the users of vue-konva. Below is my snippet example via Vue.

```
<svg
        xmlns="http://www.w3.org/2000/svg"
        version="1.1"
        xmxlink="h//www.w3.org/1999/xlink"
        xmsvgjs="h//svgjs.com/svgjs"
        :width="chartConfig.width"
        :height="chartConfig.height"
      >
        <polyline
          :points="chartPoints"
          fill="none"
          :stroke-width="strokeWidth"
          :stroke="chartLineStroke"
        ></polyline>
      </svg>
```

**Below is the actual value:**
```
<svg
        xmlns="http://www.w3.org/2000/svg"
        version="1.1"
        xmxlink="h//www.w3.org/1999/xlink"
        xmsvgjs="h//svgjs.com/svgjs"
        width="1425"
        height="3659"
      >
        <polyline
          points="1025,70,1139,100,607,130,227,160,911,190,645,220,759,250,987,280,911,310,835,340,911,370,949,400,721,430,1177,460,797,490,569,520,987,550,797,580,607,610,797,640,569,670,455,700,949,730,645,760,645,790,873,820,417,850,569,880,1063,910,911,940,949,970,759,1000,1405,1030,797,1060,683,1090,835,1120,949,1150,873,1180,303,1210,683,1240,759,1270,607,1300,759,1330,987,1360,759,1390,987,1420,645,1450,873,1480,1253,1510,835,1540,987,1570,759,1600,1063,1630,417,1660,531,1690,1139,1720,1025,1750,873,1780,1063,1810,835,1840,949,1870,911,1900,1215,1930,911,1960,721,1990,683,2020,797,2050,1329,2080,645,2110,1291,2140,721,2170,873,2200,873,2230,683,2260,949,2290,835,2320,759,2350,721,2380,569,2410,1291,2440,607,2470,1253,2500,455,2530,911,2560,721,2590,1177,2620,835,2650,303,2680,607,2710,797,2740,721,2770,417,2800,721,2830,797,2860,987,2890,683,2920,797,2950,1139,2980,759,3010,493,3040,987,3070,683,3100,683,3130,607,3160,911,3190,379,3220,911,3250,1063,3280,1177,3310,1063,3340,797,3370,949,3400,531,3430,645,3460,113,3490,455,3520,797,3550,759,3580,1177,3610,759,3640"
          fill="none"
          stroke-width="2"
          stroke="#f9333c"
        ></polyline>
      </svg>
```
