### ISSUE TITLE
Colorize image pixel in a canvas 

### ISSUE THREAD

**Issue by WhatWhatz** [konvajs/vue-konva#107]
Is there any option that enables me to colorize some pixels of a `v-image` ? similar to this : 

![image](https://user-images.githubusercontent.com/54809336/81576431-8ac24e00-93a8-11ea-9437-0e06f0ba5580.png)

**Comment by lavrton** [comment]
Yes. You can cache it and write your own filter function: https://konvajs.org/docs/filters/Custom_Filter.html#page-title
