### ISSUE TITLE
code splitting for vue konva

### ISSUE THREAD

**Issue by SreeChandan** [konvajs/vue-konva#108]
I'm pretty new to code splitting. And I have only done async import for components. 
How to remove konva from my chunk-vendors?
when I comment out vue-konva import my chunk-vendors size goes down by around 50kb. I don't how to only import vue-konva when needed.

**Comment by SreeChandan** [comment]
I just googled a bit. seems like plugins cant be imported via async. Is there any workaround to decrease my initial load?

**Comment by lavrton** [comment]
I think it is not really related to `vue-konva`.

Probably you just need to move the first `vue-konva` import into async component too.

**Comment by SreeChandan** [comment]
I have just gone through the code and found something. It solved my problem.
But I understand it would be a breaking change for others so I'm looking into keeping the default behavior the same. Please help me understand.
The solution I came up with was: 
- comment out "require("konva") at https://github.com/konvajs/vue-konva/blob/35ddc3f114cccb75f187889501dd2c8a88d87dd2/src/index.js#L6 
- and then put require("konva") at the component I need vue-konva at.
This works. I saw the chunk-vendors size go down by the size of konva.js.

Now I understand this breaks default behavior and I want to avoid that. I tried using a new plugin option that when set to false avoids importing konva and the default is to import konva. But it's not working quite right. I'm not familiar with nwb builds. Help me solve this, please.

**Comment by SreeChandan** [comment]
> I think it is not really related to `vue-konva`.
> 
> Probably you just need to move the first `vue-konva` import into async component too.

I cannot move vue-konva to any component. Plugins must be setup before creating the vue instance.
["This has to be done before you start your app by calling new Vue():"](https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin)

**Comment by SreeChandan** [comment]
ok, I got the option to work. But I had to comment out https://github.com/konvajs/vue-konva/blob/35ddc3f114cccb75f187889501dd2c8a88d87dd2/nwb.config.js#L17
. Things seem to work fine for me. But since I don't quite understand nwb builds and why that line was added in there in the first place I don't know if doing this will have any side effects.

**Comment by lavrton** [comment]
Adding a plugin AFTER app may still work. But it is important to apply it BEFORE you use `konva` components.

```js
<template>
  <stage/>
</template>

<script>
import Vue from "vue";
import VueKonva from "vue-konva";
Vue.use(VueKonva);
Vue.component(
  "stage",
  // The `import` function returns a Promise.
  () => import("./Stage")
);
</script>
```

Try it: https://codesandbox.io/s/vue-konva-async-components-jdx4f

**Comment by SreeChandan** [comment]
That worked. Many thanks for taking the time to create an example. <3
Btw Im assuming konva is being bundled into vue-konva. Is there a way you can modularise it? So that I can do import VueKonva from "vue-konva/core". Something like that. Or is that not possible?

**Comment by lavrton** [comment]
Yeah. It is possible. We did similar for `react-konva`.

**Comment by SreeChandan** [comment]
I wonder what the use case was. I assume one would need both react-konva and konva at the same time.

**Comment by SreeChandan** [comment]
Anyways since my problem is solved I don't want to take more of your time. Thanks a lot. Do consider mentioning this way of import vue-konva in the docs somewhere. Have a good day.
