### ISSUE TITLE
save/load Free drawing

### ISSUE THREAD

**Issue by godshades** [konvajs/vue-konva#109]
Hi, I have follow this: https://konvajs.org/docs/sandbox/Free_Drawing.html (Free drawing manually)
Now I can make it work in vue-konva, but how to clear, save and load what I was drawing
Can someone give me sample, thanks

**Comment by lavrton** [comment]
I guess your only way is to save such canvas as base64 string somewhere (database?). On load just draw that image.

**Comment by godshades** [comment]
@lavrton yes I have something like this
`
    <v-stage
      ref="stage2"
      :config="configKonva2"
      v-on="handlersStage"
    >
      <v-layer ref="layer2" name>
        <v-image :config="configImg"  v-on="handlersImg"></v-image>
      </v-layer>
    </v-stage>

  computed: {
    configImg: function () {
      return {
        x: 0,
        y: 0,
        image: this.canvas
      }
    }
    save () {
      localStorage.setItem('draw', this.canvas.toDataURL('image/png'))
    },
    load () {
      let draw = localStorage.getItem('draw') || '[]'

      this.configImg.image.src = draw
      this.configImg.image.addEventListener('load', function () {
        this.context.clearRect(0, 0, width, height)
        this.context.drawImage(this.configImg.image, 0, 0, this.configImg.image.width, this.configImg.image.height, 0, 0, this.canvas.width / window.devicePixelRatio, this.canvas.height / window.devicePixelRatio)
        this.configImg.image = null
      })
      this.$refs.layer2.getStage().batchDraw()
    }
`

but not work :(
