### ISSUE TITLE
canvas draw 

### ISSUE THREAD

**Issue by godshades** [konvajs/vue-konva#110]
Hi I'm design a page have multi question and answer
User can using tablet with pen to write answer to this then save as a picture

If i'm using 
```
<v-stage >
          <v-layer >
            <v-image ></v-image>
          </v-layer>
        </v-stage>
```

this will insert a blank page between question and answer div

Can someone give me advice what I need to do

**Comment by lavrton** [comment]
What exactly do you want to do? The code above will create just an empty canvas.

**Comment by piujr** [comment]
Do you want them to be able to draw and save the image? like: https://konvajs.org/docs/sandbox/Free_Drawing.html
