### ISSUE TITLE
Konva.Fast layer is deprecated. Please use "new Konva.Layer({ listening: false })" instead.

### ISSUE THREAD

**Issue by bbofrk** [konvajs/vue-konva#111]
using v-fast-layer is showing warnings, what would be the right way to use fast layer with vue-konva in the future releases?

**Comment by bbofrk** [comment]
Sorry forgot to mention, thanks for all your good work so far, apologies if the question sounds more rude than what I meant.

**Comment by lavrton** [comment]
`<v-layer :config="{ listening: false}">`
