### ISSUE TITLE
Transformer behavior on bordered rectangle

### ISSUE THREAD

**Issue by sid3r** [konvajs/vue-konva#116]
@lavrton 
thank you for the quick feedback, I've got a weird transformer behavior when I edit a rectangle strokeWidth from an input v-model, the shape of the transformer changes to a single point which moves the rectangle in diagonal :/ I guess it's normal but not wanted at all. how do I avoid that?

![issue2](https://user-images.githubusercontent.com/4179728/89713518-13dd2700-d990-11ea-861b-86125c9897a7.gif)

And by the way some warnings still pop up from konva. when binding shape config to input, even if the input type="number".
`Konva warning: "4" is a not valid value for "strokeWidth" attribute. The value should be a number.`

**Comment by lavrton** [comment]
`input type="number"` doesn't give you a number type in `target.value`. **It still a string!** So you have to convert it into the number.
