### ISSUE TITLE
多层分组嵌套时，无法通过layer.findOne('#groupId') 找组节点

### ISSUE THREAD

**Issue by Gaosir-18** [konvajs/vue-konva#119]
多层分组嵌套时，无法通过layer.findOne('#groupId') 找组节点：
环境：vue 2.6 采用vue的渲染函数render进行动态添加图形
浏览器：Google Chrome 版本 84.0.4147.125（正式版本） （64 位）
eg： list = [
  {compontent: 'KonvaGroup', config: {x: 0, y: 0, id: 'groupId_1'},   children: {compontent: 'KonvaGroup', config: {x: 0, y: 0, id: 'groupId_2'},  children: {compontent: 'KonvaGroup', config: {x: 0, y: 0, id: 'groupId_3'} } }
];
这里可以找layer.findOne('#groupId_1')  节点，但无法找到 layer.findOne('#groupId_2') 或深入嵌套的group组件节点

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by Gaosir-18** [comment]
<template>
  <div id="app">
    <v-stage :config="stage" ref="stage">
      <v-layer ref="layer">
        
        <auto-render
          v-for="item in nodeList"
          :key="item.key"
          :tag="item.component"
          :optionData="item"
        ></auto-render>
      </v-layer>
    </v-stage>
  </div>
</template>

<script>
export default {
  name: "vueKonvaDemo",

  components: {
    //Custom render component - Render function & JSX
    autoRender: {
      render: function (createElement) {
        const _createChildElement = (createElement, data) => {
          //Create a node
          const _createElement = (node) => {
            return createElement(node.component, {
              props: {
                config: node.config,
              },
              ref: node.ref,
              refInFor: true,
            });
          };
          //Create child nodes
          const _getChildrenTextContent = (children) => {
            return children.map((node) => {
              return node.children && node.children.length
                ? _getChildrenTextContent(node.children)
                : _createElement(node);
            });
          };
          //Configure child nodes
          return data.children && data.children.length
            ? _getChildrenTextContent(data.children)
            : null;
        };

        return createElement(
          this.tag, // Tag name
          {
            props: {
              config: this.optionData.config, //vue-konva Graphical configuration item
            },
            ref: this.optionData.key,
            refInFor: true,
          },
          //Configure child virtual nodes (VNodes) this.$slots.default
          _createChildElement(createElement, this.optionData) || this.$slots.default
        );
      },
      props: ["tag", "optionData"],
    },
  },

  data() {
    return {
      //Canvas configuration item
      stage: {
        width: window.innerWidth - 50,
        height: window.innerHeight - 50,
      },

      // Dynamic node rendering list
      nodeList: [
        {
          component: "vRegularPolygon",
          key: "konva_1",
          config: {
            x: 50,
            y: 50,
            sides: 5,
            radius: 20,
            fill: "black",
            id: "konva_1",
          },
        },
        {
          component: "vGroup",
          key: "konva_2",
          config: { x: 0, y: 0, id: "konva_2" },
          children: [
            {
              component: "vRegularPolygon",
              key: "konva_21",
              config: {
                x: 120,
                y: 120,
                sides: 6,
                radius: 20,
                fill: "black",
                id: "konva_21",
              },
            },
            {
              component: "vGroup",
              key: "konva_22",
              config: { x: 0, y: 0, id: "konva_22" },
              children: [
                {
                  component: "vRegularPolygon",
                  key: "konva_221",
                  config: {
                    x: 200,
                    y: 200,
                    sides: 3,
                    radius: 20,
                    fill: "black",
                    id: "konva_221",
                  },
                },
              ],
            },
          ],
        },
      ],
    };
  },

  created() {
    //Simulate the asynchronous fetch node method
    this.$nextTick(() => {
      const _stage = this.$refs.stage.getNode();
      const _grout2 = _stage.findOne('#konva_2');
      console.log(_grout2); //--> Group{_id: 4, eventListeners:{…}, attrs:{…}, index: 1, parent: Layer}


      /************************* Error *******************************/
      //Nested child nodes, Mainly node groups
      const _grout22 = _stage.findOne('#konva_22');
      console.log(_grout22); //--> undefined
      /************************* Error *******************************/


      const _shape221 = _stage.findOne('#konva_221');
      console.log(_shape221); //--> RegularPolygon{_id: 6, eventListeners: {…}, attrs: {…}, index: 1, parent: Group}
    });
  },

  // Note: translation is not good, try to read the code

};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}
</style>

**Comment by lavrton** [comment]
Is it a demo?

**Comment by Gaosir-18** [comment]
Now that's it    ^_^

**Comment by lavrton** [comment]
I am not sure why you need such weird stuff in a render. But the problem is that you don't create a node for groups:

```js
   const _getChildrenTextContent = children => {
            return children.map(node => {
              return node.children && node.children.length
                ? _getChildrenTextContent(node.children)
                : _createElement(node);
            });
          };
```

In this code, if a node has `children`, then you don't create an element for it. But I think you should.

**Comment by Gaosir-18** [comment]
Maybe I know.


This is a tool, and I don't know what the user is going to draw


thank you
