### ISSUE TITLE
Can't use vue-konva when Vue is a global and also is used locally in webpack

### ISSUE THREAD

**Issue by chepe263** [konvajs/vue-konva#120]
I'm using vue-cli/webpack to build a web app. Webpack bundles vue version 2.6.12.
The webpage I'm including my vue app has its own vue install. Vue version 2.4.0.
There's two vue, one included with webpack and the one on the webpage that I have no control and I cannot upgrade or remove.

When I include vue-konva with webpack, there's an error

```
[Vue warn]: Error in created hook: "TypeError: Cannot convert undefined or null to object"

found in

---> <VLayer>
              <VStage>
```

The issue is caused by vue-konva [attaching itself](https://github.com/konvajs/vue-konva/blob/master/src/index.js#L58) to the global vue (the one I cannot control)

```
if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(VueKonva);
}
```

Commenting out that piece of code, resolves my issue and I'm able to use vue-konva normally.

Is there a way to remove it completely or have an extra build without it?

**Comment by lavrton** [comment]
Interesting. So do you mean that you have an error because `vue-konva` is registering itself into global vue? Why it doesn't work? Can you register `vue-konva` in Vue that is under your control? Why don't you just use Vue from global, without your own import?

**Comment by chepe263** [comment]
> So do you mean that you have an error because vue-konva is registering itself into global vue? 

Yes

> Why it doesn't work?

Global vue and webpack-bundle-vue are different versions. For what I observed, there is a $listeners property somewhere but for vue, it's undefined.

> Can you register vue-konva in Vue that is under your control? 

Yes but the problem persist because konva registers itself with global vue.

>Why don't you just use Vue from global, without your own import?

Some plugins are incompatible with global vue. Importing my own vue solves most of the cases.

**Comment by lavrton** [comment]
Closing as not a priority. Also it may work better with `vue@3`

**Comment by chepe263** [comment]
I haven't tested it yet but maybe setting vue in webpack externals might help

```
/// vue.config.js
module.exports = {
  configureWebpack: {
    externals: {
      vue: "Vue"
    },
   }
}
```
