### ISSUE TITLE
How to use Konva static members

### ISSUE THREAD

**Issue by asawatzki** [konvajs/vue-konva#121]
How do I use static members from Konva namespace? 
I'm trying to change the dragButtons discribed [here](https://konvajs.org/api/Konva.html#.dragButtons__anchor).

**Comment by lavrton** [comment]
In your `script` tag:

```js

import Konva from 'konva';
Konva.dragButtons = [1, 2];
```

**Comment by asawatzki** [comment]
Thank you very much. This works!
