### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by hybridwebdev** [konvajs/vue-konva#127]
As the title states, this plugin does not work. Even using your default examples causes an error: 

`vue.min.js?ver=5.4.4:6 TypeError: Cannot read property 'add' of undefined
    at a.mounted (vue-konva.js?7591:413)
    at He (vue.min.js?ver=5.4.4:6)
    at Yt (vue.min.js?ver=5.4.4:6)
    at Object.insert (vue.min.js?ver=5.4.4:6)
    at k (vue.min.js?ver=5.4.4:6)
    at a.__patch__ (vue.min.js?ver=5.4.4:6)
    at a.e._update (vue.min.js?ver=5.4.4:6)
    at a.r (vue.min.js?ver=5.4.4:6)
    at fn.get (vue.min.js?ver=5.4.4:6)
    at fn.run (vue.min.js?ver=5.4.4:6)`

As per one of your other closed tickets, it seems your git repo does not work out of the box. Manually loading the UMD version along side konva does work.

**Comment by lavrton** [comment]
I am glad you changed your wording.

What `vue` version do you use? Can you make a demo?

All demos on the documentation site work just fine: https://konvajs.org/docs/vue/index.html

**Comment by glundgrenm** [comment]
@lavrton Hi!

Running with vue-cli in a test project with this same code here works properly, but running it in Rails + Webpacker it doesn't work. 

I've tried several versions of Konva and Vue Konva with no success. 

Do you see if i am doing something wrong or is it a bug?

ERROR:

```
[Vue warn]: Error in mounted hook: "TypeError: undefined is not an object (evaluating 'parentKonvaNode.add')"

found in

---> <VLayer>
       <App> at app/javascript/components/App.vue
         <Root>

```
package.json

```
{
  "name": "cartaosulamerica",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "5.2.1",
    "konva": "5.0.2",
    "vue": "^2.6.12",
    "vue-konva": "2.1.5",
    "vue-loader": "^15.9.5",
    "vue-template-compiler": "^2.6.12"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.11.0"
  }
}
```

app.js 

```
import Vue from 'vue/dist/vue.esm'
import App from './../components/App.vue'

import VueKonva from 'vue-konva'
Vue.use(VueKonva)

window.onload = function () {
	new Vue({
		el: '#app',
		components: { App }
	})
}
```


App.vue

```
<template>
  <v-stage :config="stage">
    <v-layer>
      <v-circle :config="{radius: 10, fill: 'red', x: 50, y: 50}"/>
      <v-circle :config="{radius: 10, fill: 'blue', x: 20, y: 20}"/>
      <v-line :config="line"/>
    </v-layer>
  </v-stage>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;

export default {
  data() {
    return {
      stage: {
        width: 200,
        height: 200
      },

      line: {
        points: [50, 50, 20, 20],
        stroke: "grey",
        strokeWidth: 3
      }
    }
  }
}
</script>
```

**Comment by hybridwebdev** [comment]
> @lavrton Hi!
> 
> Running with vue-cli in a test project with this same code here works properly, but running it in Rails + Webpacker it doesn't work.
> 
> I've tried several versions of Konva and Vue Konva with no success.
> 
> Do you see if i am doing something wrong or is it a bug?
> 
> ERROR:
> 
> ```
> [Vue warn]: Error in mounted hook: "TypeError: undefined is not an object (evaluating 'parentKonvaNode.add')"
> 
> found in
> 
> ---> <VLayer>
>        <App> at app/javascript/components/App.vue
>          <Root>
> ```
> 
> package.json
> 
> ```
> {
>   "name": "cartaosulamerica",
>   "private": true,
>   "dependencies": {
>     "@rails/webpacker": "5.2.1",
>     "konva": "5.0.2",
>     "vue": "^2.6.12",
>     "vue-konva": "2.1.5",
>     "vue-loader": "^15.9.5",
>     "vue-template-compiler": "^2.6.12"
>   },
>   "devDependencies": {
>     "webpack-dev-server": "^3.11.0"
>   }
> }
> ```
> 
> app.js
> 
> ```
> import Vue from 'vue/dist/vue.esm'
> import App from './../components/App.vue'
> 
> import VueKonva from 'vue-konva'
> Vue.use(VueKonva)
> 
> window.onload = function () {
> 	new Vue({
> 		el: '#app',
> 		components: { App }
> 	})
> }
> ```
> 
> App.vue
> 
> ```
> <template>
>   <v-stage :config="stage">
>     <v-layer>
>       <v-circle :config="{radius: 10, fill: 'red', x: 50, y: 50}"/>
>       <v-circle :config="{radius: 10, fill: 'blue', x: 20, y: 20}"/>
>       <v-line :config="line"/>
>     </v-layer>
>   </v-stage>
> </template>
> 
> <script>
> const width = window.innerWidth;
> const height = window.innerHeight;
> 
> export default {
>   data() {
>     return {
>       stage: {
>         width: 200,
>         height: 200
>       },
> 
>       line: {
>         points: [50, 50, 20, 20],
>         stroke: "grey",
>         strokeWidth: 3
>       }
>     }
>   }
> }
> </script>
> ```
> 
> HTML:
> 
> ```
> <h1>Cartão</h1>
> <div id="app">
> 	<App/>
> </div>
> ```

mind not high-jacking my ticket, and making your own?

**Comment by hybridwebdev** [comment]
I was using the UMD version of vue (not imported) from https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.min.js.
