### ISSUE TITLE
Does not work on Rails + Webpacker

### ISSUE THREAD

**Issue by glundgrenm** [konvajs/vue-konva#128]
@lavrton Hi!

Running with vue-cli in a test project with this same code here works properly, but running it in Rails + Webpacker it doesn't work. 

I've tried several versions of Konva and Vue Konva with no success. 

Do you see if i am doing something wrong or is it a bug?

ERROR:

```
[Vue warn]: Error in mounted hook: "TypeError: undefined is not an object (evaluating 'parentKonvaNode.add')"

found in

---> <VLayer>
       <App> at app/javascript/components/App.vue
         <Root>

```
package.json

```
{
  "name": "cartaosulamerica",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "5.2.1",
    "konva": "5.0.2",
    "vue": "^2.6.12",
    "vue-konva": "2.1.5",
    "vue-loader": "^15.9.5",
    "vue-template-compiler": "^2.6.12"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.11.0"
  }
}
```

app.js 

```
import Vue from 'vue/dist/vue.esm'
import App from './../components/App.vue'

import VueKonva from 'vue-konva'
Vue.use(VueKonva)

window.onload = function () {
	new Vue({
		el: '#app',
		components: { App }
	})
}
```

App.vue

```
<template>
  <v-stage :config="stage">
    <v-layer>
      <v-circle :config="{radius: 10, fill: 'red', x: 50, y: 50}"/>
      <v-circle :config="{radius: 10, fill: 'blue', x: 20, y: 20}"/>
      <v-line :config="line"/>
    </v-layer>
  </v-stage>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;

export default {
  data() {
    return {
      stage: {
        width: 200,
        height: 200
      },

      line: {
        points: [50, 50, 20, 20],
        stroke: "grey",
        strokeWidth: 3
      }
    }
  }
}
</script>
```

HTML:

```
<h1>Cartão</h1>
<div id="app">
	<App/>
</div>
```

**Comment by lavrton** [comment]
@glundgrenm can you please create a small GitHub repo where I can just clone/install and reproduce? It will help me to find the solution faster.

**Comment by glundgrenm** [comment]
Hi @lavrton thanks for the quick reply!

Here is the repo: https://github.com/glundgrenm/konva-test 

I've re-added Stimulus and Turbolinks, both Rails libraries.

In case you need guidance on running rails project locally:

- check if you have ruby 2.4.0 installed
- run `bundle install`
- run `rails s`
- Navigate to http://localhost:3000/cartao

You should see the screen and inspect the error on console.

Please ping me if you need something else!

**Comment by chepe263** [comment]
@glundgrenm  is the test-repo still available?

**Comment by glundgrenm** [comment]
hi @chepe263 i decided not using, it didn't worked.

**Comment by lavrton** [comment]
Closing the issue for now. I am not sure what to do from `vue-konva` side.
