### ISSUE TITLE
Drawing large draggable images with v-image

### ISSUE THREAD

**Issue by w-geissinger** [konvajs/vue-konva#131]
I'm currently trying to use a very large v-image to fill the stage with a background (PNG or JPG probably) that may be up to 8000x8000 pixels. I don't necessarily want to render all of those pixels until they are actually perceivable, because it seems to be making quite the performance impact.

Is there any functionality in the konva library for "subsampling" or anything that may make rendering such a large image less taxing for lower end systems?

**Comment by lavrton** [comment]
There are no such build-it functions.

First, you may try to cache it on drag with a low `pixelRatio`. The quality will drop, performance go up.

Or you can try to manually split the large image into many external canvas elements, and then just show visible on the screen.

**Comment by w-geissinger** [comment]
wow, thanks for such a fast response! I will try both of those, because either should work well for my implementation. Is there a function for detecting visibility, or should I calculate it?

**Comment by lavrton** [comment]
You have to calculate it. You may probably need to do that BEFORE you add it to the stage. Or you can use `node.getClientRect()` function.
