### ISSUE TITLE
How do I manually apply style to a text node in sceneFunc

### ISSUE THREAD

**Issue by hybridwebdev** [konvajs/vue-konva#132]
So I've stumbled across an edge case, where I need to manually render a text node via sceneFunc.

This is because we want to implement curved text functionality. The textpath element will not work for us, for a multitude of reason, including the fact it does not offer fine grained control over the curvature (as per tickets in your repo). 

So for this reason, I would like to know how to go about applying the nodes styling manually. I've tried quite a few things, and gotten a handful of styling to apply,  most notably text stroke. However, centering the text, applying font family etc is still a total mystery to me.

**Comment by lavrton** [comment]
So if you want to draw manually with custom `sceneFunc` then just use 2d context API to make your drawing. Probably you don't need to use `context.fillStrokeShape(shape);`. Just apply every style manually.

> However, centering the text, applying font family etc is still a total mystery to me.

"centering" is a manual calculation of position. font family is done via `font` property - https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font

I am not sure what else do you need.

**Comment by hybridwebdev** [comment]
Thanks for the reply. Text outline, font, shadow. Basically all available styling. Can you please elaborate on the centering calculation?

**Comment by lavrton** [comment]
Well, I am not sure what kind of answer you are looking for.

text outline - `cxt.strokeText` function.
shadow - there are several shadow properties in 2d canvas API.

> Can you please elaborate on the centering calculation?

elaborate what? You have a font size. You can measure the width of the text with `https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText` function. Then just calculate the position of the aligned text.

**Comment by hybridwebdev** [comment]
Sorry, i forgot all about this ticket over the holidays. I figured it out, using canvas standard methods/properties I was able to get it sorted. Just required doing it all manually, which I was kinda hoping to avoid. Just being a lazy dev :P

Thanks for the replies, I will mark this resolved. Hope you had good holidays.
