### ISSUE TITLE
Stage centering

### ISSUE THREAD

**Issue by gitSomeCoffee** [konvajs/vue-konva#134]
I am trying to build some very basic app for editing videos, using Vue-Konva in Vue 2.
Here's a Vue component named 'konvaStage'. It's a simple stage with a 1px black frame :

```
<template>
  <div>
    <v-stage :config='stageConfig'>
      <v-layer>
        <v-rect :config='rectConfig'></v-rect>
      </v-layer>
    </v-stage>
  </div>
</template>

<script>
  export default {
    name: 'konvaStage',
    data() {
      return {
        stageConfig: {
          width: 300,
          height: 300,
        },
        rectConfig: {
          x: 0,
          y: 0,
          width: 300,
          height: 300,
          stroke: 'black',
          strokeWidth: 1
        }
      };
    }
  }
</script>
```

Despite playing with CSS to align the stage in the component file, and also in the parent app view, the stage is always centered left, with some margin from the window border. I used both text-align and align-content properties.

How can I center the stage on the webpage ?

**Comment by gitSomeCoffee** [comment]
I just managed to find a way by wrapping the stage in a `<p align='center'> </p>` tag.
Any better way to do this ?

**Comment by gitSomeCoffee** [comment]
I may have found a solution : using a centered table with a single `td` tag.
Any other ideas ?

**Comment by lavrton** [comment]
There are many methods to do that, and they are not related to `vue-konva`. It is just CSS for containers.

https://codesandbox.io/s/vue-konva-center-the-stage-1dw3m
