### ISSUE TITLE
Using HSL filter in vue-konva

### ISSUE THREAD

**Issue by kurumbus** [konvajs/vue-konva#136]
Hey! First of all, thank you for the awesome library and a vue wrapper.

I want to apply HSL filter in vue (like here https://konvajs.org/docs/filters/HSL.html) but I guess I'm missing something obvious.

Here's sandbox I'm using (i combined this https://konvajs.org/docs/vue/Filters.html and https://konvajs.org/docs/vue/Images.html)

https://codesandbox.io/s/laughing-minsky-hmcu9?file=/src/App.vue

.getHue() seems to be working but it's either not applied or applied to wrong element.

Could you help me out?

**Comment by lavrton** [comment]
Did you take a look into console error/warnings?

**Comment by kurumbus** [comment]
OK, so after trial and error it works, for those with a similar issue:
https://codesandbox.io/s/laughing-minsky-hmcu9?file=/src/App.vue
This works.

Just maybe example here https://konvajs.org/docs/vue/Filters.html is not the best one @lavrton since if I understand correctly we don't apply filter programmatically in it  (you know with a button or something). We change colour, but noise is noise.
