### ISSUE TITLE
Is there any limit to set width / height in stage?

### ISSUE THREAD

**Issue by filsuck** [konvajs/vue-konva#138]
Hi, thank you for the plugins, 
I'm curious about how much we can set for height & maximum in stage, cause I got an error when I try to set it like this
` 
configKonva: {
        container: "container",
        width: 26850,
        height: 17520,
        draggable: true
      }
`

I'm using 
` "dependencies": {
    "core-js": "^3.6.5",
    "konva": "^7.2.2",
    "vue": "^2.6.11",
    "vue-konva": "^2.1.6"
  },`

and here's the codesandbox: https://codesandbox.io/s/gallant-elbakyan-5326r

Thank you very much.

**Comment by lavrton** [comment]
That is a browser limitation. In general, you should create stages as small as possible. If your stage is bigger than screen size, you may need to implement scrolling: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#page-title
