### ISSUE TITLE
Drag & drop creates a mismatch between shape object coordinates and shape component props

### ISSUE THREAD

**Issue by Shepard** [konvajs/vue-konva#139]
Please have a look at this sandbox: https://codesandbox.io/s/dreamy-haibt-5ydvq?file=/src/App.vue

There's a green box that can be dragged around on the page. When dropping it the idea is that the X coordinate will be whereever you dragged it but the Y coordinate will slot into one of three lanes. This works fine when dragging it from one lane to another. But when you drag the box from one place in a lane to a different place in the same lane, the shape doesn't slide back into the lane on dropping (i.e. the Y coordinate doesn't update).

The reason seems to be a mismatch between what is saved in the native Konva shape object (my assumption is dragging updates the Y coordinate in there) and what the v-rect component does with the prop.
Because you move the box within the same lane, the X coordinate changes but the code sets the Y coordinate to the same value as before. This is then handed over to the v-rect component as the config. In applyNodeProps.js there is a check if the props the component received changed compared to before. Because the Y prop didn't change it doesn't save this as an attribute in the native Konva object. So the Konva object keeps the Y value from dragging and doesn't reflect the actual prop state anymore.

I see a few ways of working around this:

* I can make sure the Y value always changes to force vue-konva to update the attribute. This can be done for example by adding a really small random number to it and hoping that it won't affect the positioning so the shape won't look offset. This is rather hackish.
* I can override dragBoundFunc and make it so that the box will already slide into one of the lanes during dragging, meaning the final Y value will already be the correct one and there won't be a mismatch. So you wouldn't be able to move the box around freely anymore. While this might be desirable in some situations it is a change in UI behaviour to how I have it at the moment and I'm not sure if I can work with that.

Can you think of any other way to get vue-konva to update the attributes properly? Any other workaround? Ideally this mismatch would be fixed in the library of course.

Please keep in mind that the sandbox is a very simplified case of the app I'm working on. In the real thing the coordinates are saved in a vuex store rather than in local data, for example.

**Comment by lavrton** [comment]
`vue-konva` updates the node instance only when a property is changed. So if your `y` is the same in your props, `vue-konva` doesn't force update it so the old value (changed by the user) will be still there. 

You can:
1. Use your hacking workaround
2. Manually set position on `dragend` event: `e.target.y(dataFromYourStore)`

**Comment by Shepard** [comment]
I know but my problem is that the prop value doesn't match the actual value in the attributes anymore. So there's an inconsistency. And there's no way to orderly fix this from the props side.

I get that the dragging functionality needs some control over the coordinates of the shape and that this isn't immediately reflected in the props. But I would argue that once dragging is over the framework should fix this inconsistency for me. Would you not agree?

Fixing the position in `dragend` could be a way if this was just a very simple application. However in my case the `dragend` event triggers an action which calculates new positions for many items (because they can influence each other) and then updates the store - which in turn triggers the shape to be rerendered.

**Comment by lavrton** [comment]
Ok. That makes sense. I just added `__useStrictMode` support for all nodes in `vue-konva`. https://github.com/konvajs/vue-konva#strict-mode

We have a similar concept in `react-konva`: https://github.com/konvajs/react-konva#strict-mode

I believe using it you can solve your issue.

**Comment by Shepard** [comment]
That did indeed solve the problem for me, thanks!
