### ISSUE TITLE
stage.findOne() returning undefined, despite stage and parameters being correctly defined

### ISSUE THREAD

**Issue by w-geissinger** [konvajs/vue-konva#140]
I am attempting to use a modified version of the example for transforming rectangles, shown [here](https://konvajs.org/docs/vue/Transformer.html).

I had this previously working with `currentPolySet`, as is in the example. I have since migrated all of my rectangle data retrieval to a `vuex` store, and have a mapped getter (`getRects`) to essentially serve as my `currentPolySet` for reading, then push changes to the store as necessary. Now, `stage.findOne('.' + selectedShapeName)` returns undefined, despite me having clarified in console right before running the function that both `stage` and `selectedShapeName` both have the expected values, and `selectedShapeName` having been pulled directly from a rect being clicked on.

My question is: Am I introducing problems by attempting to use a mapped getter as the source for the rectangle data? I have no issues loading in rectangles, just finding them using `stage.findOne`.

**Comment by w-geissinger** [comment]
After some investigation, it seems that `selectedShapeName` must have no spaces. Finding the shape works fine once I removed the spaces from `selectedShapeName`. Whether this is intentionally implemented this way or not, I have since solved the ambiguity I was facing. I will leave the issue for you to resolve in the case that this is an unintended consequence of the way `findOne()` is written.

**Comment by lavrton** [comment]
A name with a space interpreted as several names. All spaces from `query` parameter of `find` and `findOne` method are moved.

I will add a note about that into docs.
