### ISSUE TITLE
Canvas height is the double of the defined stage height

### ISSUE THREAD

**Issue by elioscordo** [konvajs/vue-konva#146]
Hello, thank you for the lib.
I noticed that the canvas height is the double of the height declared in the stage function 

```
  <k-stage  :config="configStage()">
            <k-layer>

...
 configStage() {
                return { 
                    'width':300, 
                    'height': 400
                }
            }
```

quick screenshot of the resulting html
![image](https://user-images.githubusercontent.com/477426/113473605-c0fa3780-946a-11eb-8ca8-5c8a4df3211e.png)

is it not weird?

Thank you!

**Comment by lavrton** [comment]
It is expected behavior. It allows drawing hight quality results on HDP devices.
You can learn more here: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
