### ISSUE TITLE
vue subcomponent

### ISSUE THREAD

**Issue by mkargi** [konvajs/vue-konva#148]
is it possible to have vue subcomponents without a layer inside?
for example:

```
<stage>
  <v-layer>
    <MyComponent1 />
    <MyComponent2 />
  </v-layer>
</stage>

MyComponent1:

<template>
  <v-text :config="config" />
</template>
```

For me this is not working. If i move the layer inside the MyComponent, this is working. But so i have 2 layer instead of one.. Thanks for help

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by mkargi** [comment]
Hi lavrton. I setup a simple example in codesandbox.io and there it works like expected. Then i found out, that i am currently not using the latest konva version. I updated konva in my project and now it works fine.
