### ISSUE TITLE
Very nice Library !  Trying to convert following example to vuejs:

### ISSUE THREAD

**Issue by dggb** [konvajs/vue-konva#157]
var width = 960;
    var height = 600;

    var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height,
    });

    var layer = new Konva.Layer();
    stage.add(layer);
    let currentShape;

    document.getElementById('Rect').addEventListener("click", function () {

        let item = new Konva.Rect({
            x: 20,
            y: 20,
            width: 100,
            height: 50,
            fill: 'green',
            stroke: 'black',
            strokeWidth: 4,
            draggable: true,
        });
        var tr = new Konva.Transformer();
        layer.add(tr);
        layer.add(item);
        tr.nodes([item]);
        layer.draw();
    });
    var menuNode = document.getElementById('menu');

    document.getElementById('delete-button').addEventListener('click', () => {
        var tr = layer.find('Transformer').find(tr => tr.nodes()[0] === currentShape);
        tr.destroy();
        currentShape.destroy();
        layer.draw();
    });

    window.addEventListener('click', () => {
        menuNode.style.display = 'none';
    });

    stage.on('contextmenu', function (e) {
        e.evt.preventDefault();
        if (e.target === stage) {
            return;
        }
        currentShape = e.target;

        menuNode.style.display = 'initial';
        var containerRect = stage.container().getBoundingClientRect();
        menuNode.style.top =
            containerRect.top + stage.getPointerPosition().y + 4 + 'px';
        menuNode.style.left =
            containerRect.left + stage.getPointerPosition().x + 4 + 'px';
    });

**Comment by lavrton** [comment]
What did you try?

**Comment by dggb** [comment]
I tried it like this. 
But I want to try like that JavaScript.

<template>
<div>
    Click on canvas to create a cirlce.
    <a href=".">Reload the page</a>. Circles should stay here.
    <v-stage ref="stage" :config="stageSize" @click="handleClick">
      <v-layer ref="layer">
        <v-circle
          v-for="item in list"
          :key="item.id"
          :config="{
            x: item.x,
            y: item.y,
            radius: 50,
            fill: 'red',
          }"
        ></v-circle>
      </v-layer>
      <v-layer ref="dragLayer"></v-layer>
    </v-stage>
  </div>
</template>

<script>
import Vue from 'vue';
import VueKonva from 'vue-konva';

Vue.use(VueKonva);

const width = 960;
const height = 600;

export default {
  data() {
    return {
      list: [{ x: 100, y: 100, radius: 50, fill: "blue" }],
      stageSize: {
        width: width,
        height: height,
      },
    };
  },
  methods: {
    handleClick(evt) {
      const stage = evt.target.getStage();
      const pos = stage.getPointerPosition();
      this.list.push(pos);

    //   this.save();
    },

    // load() {
    //   const data = localStorage.getItem("storage") || "[]";
    //   this.list = JSON.parse(data);
    // },

    // save() {
    //   localStorage.setItem("storage", JSON.stringify(this.list));
    // },
  },
  mounted() {
    this.load();
  },
};
</script>

**Comment by dggb** [comment]
`<template>
<div>
    Click on canvas to create a cirlce.
    <a href=".">Reload the page</a>. Circles should stay here.
    <v-stage ref="stage" :config="stageSize" @click="handleClick">
      <v-layer ref="layer">
        <v-circle
          v-for="item in list"
          :key="item.id"
          :config="{
            x: item.x,
            y: item.y,
            radius: 50,
            fill: 'red',
          }"
        ></v-circle>
      </v-layer>
      <v-layer ref="dragLayer"></v-layer>
    </v-stage>
  </div>
</template>

<script>
import Vue from 'vue';
import VueKonva from 'vue-konva';

Vue.use(VueKonva);

const width = 960;
const height = 600;

export default {
  data() {
    return {
      list: [{ x: 100, y: 100, radius: 50, fill: "blue" }],
      stageSize: {
        width: width,
        height: height,
      },
    };
  },
  methods: {
    handleClick(evt) {
      const stage = evt.target.getStage();
      const pos = stage.getPointerPosition();
      this.list.push(pos);

    //   this.save();
    },

    // load() {
    //   const data = localStorage.getItem("storage") || "[]";
    //   this.list = JSON.parse(data);
    // },

    // save() {
    //   localStorage.setItem("storage", JSON.stringify(this.list));
    // },
  },
  mounted() {
    this.load();
  },
};
</script>`

**Comment by dggb** [comment]
<template>
  <v-stage
    ref="stage"
    :config="stageSize"
  >
    <v-layer
      ref="layer"
    >
      <v-label
        v-for="annotation in annotations"
        :key="annotation.id"
        :config="{
          x: annotation.x,
          y: annotation.y
        }"
      >
        <v-tag
          :config="{
            fill: 'green',
            pointerDirection: 'down',
            pointerWidth: 10,
            pointerHeight: 10,
            lineJoin: 'round',
            shadowColor: 'black',
            shadowBlur: 10,
            shadowOffsetX: 10,
            shadowOffsetY: 10,
            shadowOpacity: 0.5,
            cornerRadius: 5
          }"
        />
        <v-text
          :config="{
            text: annotation.text,
            fontFamily: 'Calibri',
            fontSize: 18,
            padding: 10,
            fill: 'black'
          }"
        />
      </v-label>
    </v-layer>
  </v-stage>
</template>

<script>

import Vue from 'vue'
import VueKonva from 'vue-konva'
import Konva from 'konva'

Vue.use(VueKonva)
Vue.use(Konva)

export default {
  data () {
    return {
      stageSize: {
        width: 800,
        height: 800
      },
      annotations: [
        {
          id: '1',
          x: 100,
          y: 100,
          text: 'test'
        }
      ]
    }
  }
}
</script>

**Comment by dggb** [comment]
var width = 960;
var height = 600;

var stage = new Konva.Stage({
    container: 'container',
    width: width,
    height: height,
});

var layer = new Konva.Layer();
stage.add(layer);
let currentShape;

document.getElementById('Rect').addEventListener("click", function () {

    let item = new Konva.Rect({
        x: 20,
        y: 20,
        width: 100,
        height: 50,
        fill: 'green',
        stroke: 'black',
        strokeWidth: 4,
        draggable: true,
    });
    var tr = new Konva.Transformer();
    layer.add(tr);
    layer.add(item);
    tr.nodes([item]);
    layer.draw();
});
var menuNode = document.getElementById('menu');

document.getElementById('delete-button').addEventListener('click', () => {
    var tr = layer.find('Transformer').find(tr => tr.nodes()[0] === currentShape);
    tr.destroy();
    currentShape.destroy();
    layer.draw();
});

window.addEventListener('click', () => {
    menuNode.style.display = 'none';
});

stage.on('contextmenu', function (e) {
    e.evt.preventDefault();
    if (e.target === stage) {
        return;
    }
    currentShape = e.target;

    menuNode.style.display = 'initial';
    var containerRect = stage.container().getBoundingClientRect();
    menuNode.style.top =
        containerRect.top + stage.getPointerPosition().y + 4 + 'px';
    menuNode.style.left =
        containerRect.left + stage.getPointerPosition().x + 4 + 'px';
});``

**Comment by lavrton** [comment]
> why not this.currentShape target undefined ??

Because `this` is not what you expect. You need to learn more about contexts in js. In should, you need to use arrow functions instead of `function() {}`
