### ISSUE TITLE
Save/Load Stage

### ISSUE THREAD

**Issue by tserkov** [konvajs/vue-konva#16]
How would you best recommend implementing the save/load features in a Vue-friendly manner?

For my use case, I'm required to store the state of the Stage in either LocalStorage or a server-side database, and be able to restore it at a later time.

#### Konva Doc References:
- [Save HTML5 Canvas Stage as JSON String](https://konvajs.github.io/docs/data_and_serialization/Serialize_a_Stage.html)
- [Load Stage with JSON String](https://konvajs.github.io/docs/data_and_serialization/Simple_Load.html)

Thanks in advance!

**Comment by forrest-wilson** [comment]
I'm in the same situation. I have a method for saving the Konva Stage in a JSON file but no way of loading that data back into my app.

@tserkov I don't know whether you've seen the docs, but there is an easy way to stringify the Konva stage using the ```getStage()``` and ```toJson()``` method.

The way I do it is:

```
<template>
  <div>
    <v-stage :config="konvaConfig" ref="stage" @click="clickHandler">
      ...
    </v-stage>
  </div>
</template>

<script>
export default {
  data () {
    return {
      konvaConfig: {
        width: 1000,
        height: 1000
      }
    }
  },
  methods: {
    clickHandler () {
      let stageJson = this.$refs.stage.getStage().toJson()
      // Do whatever you want with the JSON string now
    }
  }
}
</script>
```

Any insights into loading in a stage would be much appreciated!

**Comment by lavrton** [comment]
@sololance  did you look at the demo above?

**Comment by sololance** [comment]
@lavrton sure, what I can't understand is how to load objects back without using in template _"v-text", "v-circle", "v-rect" and etc._

Here is a demo what I meant by dynamic objects: https://codesandbox.io/s/lr7qyn958l

Thanks!

**Comment by lavrton** [comment]
Ah. I see. You are using `konva` manually, without `vue-konva` (just a stage from it). In case of manual saving/loading take a look here: https://konvajs.github.io/docs/data_and_serialization/Complex_Load.html

But my recommendation is to use the power of `vue-konva` and do not create shapes manually. Just define a state of the app. And draw canvas from the state in your template.
