### ISSUE TITLE
Not able to drag and transform rectangles in konva js when loaded with Konva.Node.create

### ISSUE THREAD

**Issue by dggb** [konvajs/vue-konva#160]
Vue Link : https://codesandbox.io/s/testjsontransformer-vzchn?file=/src/App.vue

I can't understand no matter how hard I think about it.

Why Cannot read property '_getPointerById' of undefined ??

**Comment by lavrton** [comment]
Works just fine for me. How to reproduce it?

**Comment by dggb** [comment]
I've solved the above problem, but We have a new problem.

I put some text in the box. This isn't part of the Transformers group. 

Why is this happening?

Vue Link : https://codesandbox.io/s/testjsontransformer-forked-0v97n

Can you possibly solve this problem??

**Comment by lavrton** [comment]
Because you are attaching transformer to the rectangle shape. Not the group. Just attach it into the group instead.

**Comment by dggb** [comment]
Thank you. You've helped me solve this problem.

Vue Link : https://codesandbox.io/s/testjsontransformer2-bpwd3?file=/src/App.vue

I'll ask you again if there's a problem later!
