### ISSUE TITLE
Electron Renderer - Uncaught Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/konva/lib/index-node.js

### ISSUE THREAD

**Issue by dzunglaviet** [konvajs/vue-konva#163]
Hi
I use vue-konva with Electron webpack, got this error.

Here is my package.json

{
  "name": "SHCN-Migration",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "dev": "electron-webpack dev",
    "compile": "electron-webpack",
    "dist": "yarn compile && electron-builder",
    "dist:dir": "yarn dist --dir -c.compression=store -c.mac.identity=null"
  },
  "dependencies": {
    "ant-design-vue": "^1.7.6",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link-http": "^1.5.17",
    "axios": "^0.21.1",
    "electron": "^13.2.1",
    "esm": "^3.2.25",
    "graphql": "^15.5.1",
    "graphql-tag": "^2.12.5",
    "konva": "^8.1.3",
    "source-map-support": "^0.5.16",
    "vue": "^2.6.14",
    "vue-konva": "^2.1.7",
    "vue-router": "^3.5.2",
    "vuex": "^3.6.2",
    "vuex-map-fields": "^1.4.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "electron-builder": "^22.4.1",
    "electron-webpack": "^2.8.2",
    "electron-webpack-vue": "^2.4.0",
    "vue-devtools": "^5.1.4",
    "webpack": "~4.42.1"
  }
}

**Comment by Aravinda93** [comment]
@dzunglaviet 
Even I am getting the error, Did you ever find the resolution for the issue? if so please let me also know.

when I use `vue-konva`. I am running into the following issue:
```
Must use import to load ES Module: /Users/myName/projects/projectName/node_modules/konva/lib/index-node.js require() of ES modules is not supported. 
require() of /Users/myName/projects/projectName/node_modules/konva/lib/index-node.js from /Users/myName/projects/projectName/node_modules/vue-konva/umd/vue-konva.js is an ES module file as it is a .js file whose nearest parent package.json 
contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index-node.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/myName/projects/projectName/node_modules/konva/package.json.
```

**Comment by lavrton** [comment]
Do you use it in nodejs env? Like nuxtjs?

**Comment by Aravinda93** [comment]
@lavrton Thanks for your response. I am not sure if I am following what you are asking. I am using it within my `nuxtjs` application. I did the following steps:

1. Install `npm install vue-konva konva --save ` and `npm install canvas --save`

Following is my complete code sample:
```
<template>
  <v-stage :config="configKonva">
    <v-layer>
      <v-circle :config="configCircle" />
    </v-layer>
  </v-stage>
</template>

<script>
import Vue from 'vue'
import VueKonva from 'vue-konva'

Vue.use(VueKonva)

export default {
  data () {
    return {
      configKonva: {
        width: 200,
        height: 200
      },
      configCircle: {
        x: 100,
        y: 100,
        radius: 70,
        fill: 'red',
        stroke: 'black',
        strokeWidth: 4
      }
    }
  }
}
</script>

<style>
body {
  margin: 0;
  padding: 0;
}
</style>
```

**Comment by lavrton** [comment]
Should not be the issue with the last konva.
