### ISSUE TITLE
Image not working with fillPatternImage 

### ISSUE THREAD

**Issue by JanErligen** [konvajs/vue-konva#165]
Hi, 

I'm trying to apply an image to a v-rect by adding an image to the fillPatternImage property. Unfortunately I'm so far unsuccessful. The config object for my rect does have an image object in it. This is the result when logging it:

```javascript
Object
        fill: (...),
        fillPatternImage: img
	        accessKey: ""
	        align: ""
	        alt: ""
	        ariaAtomic: null
	        ...
	        outerHTML: "<img width=\"168\" height=\"85\" src=\"https://i.i
	        ...
        height: (...)
        ...
```
I'm loading the image like in the example: 
```javascript
	let image = new Image();
	image.onload = () => {
		this.configTiles[i].config.fillPatternImage = image;
	}
	image.src = 'https://i.imgur.com/jBW55eL.jpeg';
```

Although the official documentation is like:
```javascript
shape.fillPatternImage(image);
```

Making my fillPatternImage a function results in an error stating it's not a function. 
I've tried direct links, Nuxt refs (this.$refs), axios get's for the image and some things I cannot remember anymore.

Any ideas on what I'm doing wrong? If more info is required I'm happy to provide it.

Thanks in advance.

**Comment by lavrton** [comment]
Can you make a codesandbox demo?

**Comment by JanErligen** [comment]
I created a very dumbed down version of what I have in my Nuxt setup. The console log shows that there is an image. Although here it shows it as the html image element whilst in my setup I have it as in my first post.

https://codesandbox.io/s/eager-murdock-j4itr?file=/src/App.vue

**Comment by lavrton** [comment]
Fixed version: https://codesandbox.io/s/quirky-sky-hcf15?file=/src/App.vue

1. You may need to use `fillPriority` if you have both `fill` and `fillPatternImage` properties on the node.
2. You need to define `fillPatternImage` on your default config (as a simple `null` or `undefined`) to make it observable. Otherwise, Vue is not updating the template.

**Comment by JanErligen** [comment]
Thank you!
