### ISSUE TITLE
Updating shapes points doesn't re-render layer

### ISSUE THREAD

**Issue by robertsLando** [konvajs/vue-konva#167]
When adding points to a v-line in mouseMove event the shape is not updated correctly. Mind that I'm using `push` and `splice` methods to add/remove/replace them as suggested by vue for observable arrays

**Comment by lavrton** [comment]
`vue-konva` may not see such updates. Try to use new arrays.

**Comment by robertsLando** [comment]
@lavrton Is there a way to manually trigger an update?

**Comment by lavrton** [comment]
Use `ref` api to get access to Konva instances. Then you `layer.batchDraw()`
