### ISSUE TITLE
How to access Konva.hitOnDragEnabled with vue-konvas

### ISSUE THREAD

**Issue by Cuke7** [konvajs/vue-konva#179]
Hello everyone,

I'm trying to replicate this [exemple](https://konvajs.org/docs/sandbox/Multi-touch_Scale_Stage.html), using vue-konva (in a Nuxt environement).

The plugin itself is working fine, I add it to the vue instance via:

```
import Vue from "vue";
import Vue from "vue";
import VueKonva from "vue-konva";
Vue.use(VueKonva);
```

My issue is that I need to acess the **hitOnDragEnabled** property as explained in the previous exemple. 

How can I do this in Vue ? I suppose it's something like:

`this.$Konva.hitOnDragEnabled` or something but I can't figure it out and StackOverflow is no help this time...

Thanks a lot !

**Comment by lavrton** [comment]
Just add

```js
import Konva from 'konva';
Konva. hitOnDragEnabled = true;
```
