### ISSUE TITLE
Multiple Mount When Import

### ISSUE THREAD

**Issue by Nunkung** [konvajs/vue-konva#187]
<img width="551" alt="Screen Shot 2565-03-16 at 12 57 24" src="https://user-images.githubusercontent.com/7234195/158526218-93f4af54-dfa0-4952-8f62-1c7780495eb9.png">
This is the log i print.
<img width="740" alt="Screen Shot 2565-03-16 at 12 59 03" src="https://user-images.githubusercontent.com/7234195/158526238-5017cab2-1d90-4431-8097-f1bbc3587e4d.png">
This is the log when i just import VueKonva.
<img width="485" alt="Screen Shot 2565-03-16 at 13 00 27" src="https://user-images.githubusercontent.com/7234195/158526303-fabf8f40-9cbf-43ce-ada2-e427cc58904c.png">
This is mount and then find parent

I Use 
Vue.js 2.6.14  
konva 7.2.5
vue-konva 2.1.7
laravel-mix 6.0.43

I don't know why they call mount again and again

**Comment by lavrton** [comment]
Can you make a reproducible demo of the issue?

**Comment by Nunkung** [comment]
All i do is https://konvajs.org/docs/vue/ quick start  1 2 3 and run

**Comment by Nunkung** [comment]
<img width="1391" alt="Screen Shot 2565-03-21 at 16 12 52" src="https://user-images.githubusercontent.com/7234195/159232476-9745fe69-71b3-4742-87a7-b974e9a309cb.png">
<img width="1107" alt="Screen Shot 2565-03-21 at 16 13 13" src="https://user-images.githubusercontent.com/7234195/159232489-be564158-a08b-4511-b2cf-d0a64f9c3f60.png">

**Comment by Nunkung** [comment]
<img width="421" alt="Screen Shot 2565-03-21 at 16 53 19" src="https://user-images.githubusercontent.com/7234195/159238417-65981333-6810-40e3-a215-202b372cd72f.png">
when i use version lib in red line it's has a problem like above.
but when i use green line it's work.
<img width="670" alt="Screen Shot 2565-03-21 at 16 55 34" src="https://user-images.githubusercontent.com/7234195/159238685-91ecafa7-fdd1-4c18-869b-9bebacb7f038.png">
because of mix ?
