### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by andresilva-cc** [konvajs/vue-konva#189]
I followed the instructions on `README`, but console gives me the following error:

![image](https://user-images.githubusercontent.com/15927886/160739607-b47252c1-1c92-4747-955c-b681d64b9602.png)

Also when I inspect the generated HTML, instead of the stage component it renders:

![image](https://user-images.githubusercontent.com/15927886/160739643-10a3239a-5dba-446e-9bfd-e564b7a66333.png)

Repository to reproduce the error: https://github.com/andresilva-cc/vue-konva-error

**Comment by lavrton** [comment]
vue version 2 or 3?

**Comment by andresilva-cc** [comment]
> vue version 2 or 3?

2

**Comment by lavrton** [comment]
Try `npm install vue-konva@2`.

**Comment by andresilva-cc** [comment]
It worked. I read you talking about Vue 3 support so I haven't imagined that there was a 3.0.0 version published lol

Thanks!
