### ISSUE TITLE
"e.target.getStage() is not a function" when using Transformer with Vue 3

### ISSUE THREAD

**Issue by bowtietech** [konvajs/vue-konva#192]
You get the error (in Chrome, OS X) "e.target.getStage() is not a function" when trying to use Transformer code, pulled from demo. Demo in docs does not currently work, either. 

Can be seen at https://konvajs.org/docs/vue/Transformer.html

That aside, super rad library, thank you!

**Comment by lavrton** [comment]
Good catch.

There is an issue with `Vue 3` for double event trigger on stage component. As a workaround, you can filter event function with `e.evt` check. I updated the demo.

I hope `vue-konva` will have a fundamental fix for that soon.
