### ISSUE TITLE
fillPatternImage not working in Firefox

### ISSUE THREAD

**Issue by alexcrawford** [konvajs/vue-konva#193]
I'm trying to create a cropping tool that allows a user to upload an image, crop it, and preview the image on an existing Konva canvas.

In Firefox, the image seems to be rendered as a black fill, rather than the actual image.

I've put together a sandbox which replicates the issue:
https://codesandbox.io/s/wonderful-lamarr-r8bx75?file=/src/App.vue

The issue occurs once you upload an image and attempt to crop it.

The issue does not occur in Google Chrome.

Is this a bug or have we not implemented it correctly?

Thanks!

**Comment by lavrton** [comment]
You need to set image only when it is loaded: https://codesandbox.io/s/mutable-shape-7gdrvb

That way it works ok for me in FF.

**Comment by alexcrawford** [comment]
Thanks so much, hugely appreciated.
