### ISSUE TITLE
Update to last Konva version

### ISSUE THREAD

**Issue by Ldoppea** [konvajs/vue-konva#20]
Hi @rafaesc ,

Would it be possible to update the Konva dependency to its last version (2.2.2) so we can have new functionalities?

Example of implemented ones : 
- Automatic validations for many attributes : https://twitter.com/lavrton/status/1031837649236107264
- Konva.Transformer : https://twitter.com/lavrton/status/974174592527773697
- Many bug fixes : https://github.com/konvajs/konva/blob/master/CHANGELOG.md

Thanks

**Comment by Ldoppea** [comment]
@lavrton do you know if there may be breaking changes in konvajs since v1.7.6?

**Comment by lavrton** [comment]
It should be safe to update konva version. But as I understand you can update `konva` version in your project. Version change in `vue-konva` is not required.

**Comment by rafaesc** [comment]
@lavrton @Ldoppea, yes, konva isn't a dependency in the project, so you can update.

But if there is a new feature that is not supported in vue-konva, you can create an issue, to fix it

**Comment by Ldoppea** [comment]
> But as I understand you can update konva version in your project. Version change in vue-konva is not required.

>@lavrton @Ldoppea, yes, konva isn't a dependency in the project, so you can update.

Ah I did not think about that, I'll try it.

> But if there is a new feature that is not supported in vue-konva, you can create an issue, to fix it

I think this will be the case for `Konva.Transformer`. If so, I'll try to propose a merge request.
Will adding it to `KONVA_NODES` in [lib.js](https://github.com/konvajs/vue-konva/blob/master/src/lib.js) be sufficient? Or do I need to make changes somewhere else?

**Comment by rafaesc** [comment]
@Ldoppea, yes, with that change it should work well

**Comment by lavrton** [comment]
@Ldoppea you are right. `Transformer` is not a classic node. I didn't find the better solution to implement it with `react-konva`, so I just made this: https://konvajs.github.io/docs/react/Transformer.html

Probably `vue-konva` can work in the same way.
