### ISSUE TITLE
How do you use this from TypeScript?

### ISSUE THREAD

**Issue by jez9999** [konvajs/vue-konva#202]
The example code of using a `ref` to access the stage gives an error in TypeScript:

```
<script setup lang="ts">
    import { ref } from 'vue';
    const stageRef = ref(null);
    const stage = stageRef.value.getStage(); // error
</script>
<template>
    <v-stage ref="stage" :config="stage"></v-stage>
</template>
```

There's a TypeScript error that `stageRef.value` is possibly `null` because of the initial `null` value passed into the `ref`.  But what type should the `ref` be?  I'm thinking possibly `ref<Stage | null>` but that's a total guess.  How can I find out what type the ref should be?

**Comment by lavrton** [comment]
`ref<Stage | null>` should be good.
