### ISSUE TITLE
[Vue warn]: Error in mounted hook: "Error: Konva error: You may only add layers to the stage."

### ISSUE THREAD

**Issue by rdgbrezolin** [konvajs/vue-konva#205]
I'm applying the same example from the documentation (link) and it doesn't work.

Example: https://konvajs.org/docs/vue/Shapes.html

Error: [Vue warn]: Error in mounted hook: "Error: Konva error: You may only add layers to the stage."

It seems to me some error with version/installation. I can't run anything related to konva.

"konva": "^8.3.14",
"vue-konva": "^2.1.7",
"vue": "^2.5.22"

**Comment by lavrton** [comment]
Can you make a demo? Like a codesandbox?

**Comment by rdgbrezolin** [comment]
![image](https://user-images.githubusercontent.com/60623792/202287039-55152bd1-41a3-4179-a847-b4a805abe7a8.png)

**Comment by rdgbrezolin** [comment]
@lavrton Can you help me? I can't run any examples from konva.

**Comment by lavrton** [comment]
I need a small demo.
