### ISSUE TITLE
transformer configs?

### ISSUE THREAD

**Issue by dakiba** [konvajs/vue-konva#208]
I tried the example:
https://konvajs.org/docs/vue/Transformer.html

But how can I give the transformer the configs? Like here? https://konvajs.org/docs/select_and_transform/Keep_Ratio.html
I have to disable the rotation and keep the ratio ...

Greetings

**Comment by lavrton** [comment]
Did you try anything? You pass the same way as props in other shapes. Directly via property or using `:confg`
