### ISSUE TITLE
Does it have a Batch Draw method? And how do I use it?

### ISSUE THREAD

**Issue by muuma** [konvajs/vue-konva#21]
I want to draw the canvas in batches, but if the image is too many, the browser will crash. For example, I want to generate a full arrangement of ten images, and use these results to render the canvas, then the browser will crash.

[http://test-liveme-cms-datastore.s3.amazonaws.com/liveme_new_ad/64ee2dc108334b6043aa4a19e195dec6.png](url)

**Comment by lavrton** [comment]
The issue is too old and probably not relevant anymore. If it is still relevant, please provide more info.
