### ISSUE TITLE
[Vue2] Cannot read properties of undefined (reading 'add')

### ISSUE THREAD

**Issue by gduliscouet-ubitransport** [konvajs/vue-konva#210]
## Version

Vue 2.6.14 (with vue-cli, webpack...)
VueKonva 2.1.7
Konva 8.3.2

## Bug description

When loading even a simple template like:

```html
        <v-stage :config="configKonva">
            <v-layer>
                <v-circle :config="configCircle"></konva-circle>
            </v-layer>
        </v-stage>
```

We have this error 2 times: `TypeError: Cannot read properties of undefined (reading 'add')`

But **only on the production build**, when integrated in a more complex environment (it is working when serving it with hot reload)

## Bug analizis

The errors comes from the `v-layer` and `v-circle` [onMounted hook](https://github.com/konvajs/vue-konva/blob/e5d156ee60ac145fa2a5aaef80f8ef596b966a5e/src/components/KonvaNode.js#L58) where it cannot find any "parent konva".

The cause is:
- Due to our complex production environment we have a Vue insalled from CDN (so on `window.Vue`) => we need it for older Vue integrations, without a build step (same system, multiple approaches...)
- [Konva detects that and install itself](https://github.com/konvajs/vue-konva/blob/e5d156ee60ac145fa2a5aaef80f8ef596b966a5e/src/index.js#L59) on this "CDN Vue"
- Vue doesn't react well to this "usage of multiple Vue" and its parent child structure is broken (ex: the `$parent` of `v-layer` is not `v-stage`)

## Proposed solution

Could we check also if Konva is installed with CDN ? People who deliberatly take the CDN "no build step approach" will have both.

~It fixed the bug for us~

EDIT: I realised Konva [always installs itself](https://github.com/konvajs/konva/blob/888fbf32549a8ad78584b0011503cdeb0938453a/src/Global.ts#L191) on `window` even in the build approach. So we need another solution :/

```js
if (typeof window !== 'undefined' && window.Vue && window.Konva) {
  window.Vue.use(VueKonva);
}
```

**Comment by gduliscouet-ubitransport** [comment]
Hello @lavrton,

I still opened the issue, but it seems you have no maintenance branch for VueKonva 2 ? And VueKonva 3 is not compatible with Vue 2 ?

Am I wrong ? Could we still have a `v2` maintenance branch ? Then I could open a pull request.

I had a similar bug when trying to do tests with VueKonva in local (`npm link` https://docs.npmjs.com/cli/v8/commands/npm-link). This one was due to a leftover `Vue.component('v-stage'...` [outside of the plugin installation](https://github.com/konvajs/vue-konva/blob/e5d156ee60ac145fa2a5aaef80f8ef596b966a5e/src/components/Stage.js#L4) (so not using the "good `Vue`" again)

**Comment by lavrton** [comment]
We can create a maintenance branch for `v2`. It will be good to find the last working git commit for it and create a branch. I don't have much time to do that by myself.

**Comment by gduliscouet-ubitransport** [comment]
Thank you, but I did not find any good way to disable the "auto-install" when it is not wanted :/ And it would be to breaking to remove it

**Comment by gduliscouet-ubitransport** [comment]
Anyway, the reason of the bug is not clear enough. We'll try to find a way to remove the global Vue from the page. You can close the issue
