### ISSUE TITLE
Rescalable canvas/stage

### ISSUE THREAD

**Issue by ThomasvanHoutum** [konvajs/vue-konva#211]
Hi all,
I am looking for a way to rescale the canvas when the window gets rescaled, so the user can always use 100% of their screen.
To visualize what I'm looking for with the vue konva demo:
When the canvas gets created:
![image](https://user-images.githubusercontent.com/123364387/225349163-bb132728-4ad7-4186-9a70-cf03097af063.png)

After rescaling the window:
![image](https://user-images.githubusercontent.com/123364387/225349340-a16e4b4c-a239-4ba8-97c1-72bfb8cee4cc.png)

I was wondering if I can rescale the canvas with something like an event like addEventListener("resize").

Thanks in advance!

**Comment by geoffgscott** [comment]
Yes you need to reactively update the stage configs width and height. onResize could be used but won't handle layout changes unrelated to screen resizing (like sidebars pushing the view window smaller). Resize observers are able to track container level size changes and would likely be the better tool here.

```javascript
// Konva Stage config
const config = reactive({
    width: 100,
    height: 100,
    draggable: true,
    background: '#DDDDDD',
})

// Resize observer attached div that wraps v-stage
const ro = new ResizeObserver((entries) => {
    for (const entry of entries) {
        const cr = entry.contentRect
        config.width = cr.width
        config.height = cr.height
    }
})
ro.observe(element)
```
