### ISSUE TITLE
reading out object variables

### ISSUE THREAD

**Issue by jerryComo** [konvajs/vue-konva#213]
Hi - I've created this from one of the demos 

  var animal = new Konva.Image({
              image: image3,
              width: 256,
              height: 256,
              x: loc.x,
              y: loc.y,
              name:"bob",
    });

   animalList.push(animal);

   later when iterating through this array i want to read that name - animal.name - but instead of "bob" I get the following

"
function() {
      if (arguments.length) {
        this[setter](arguments[0]);
        return this;
      }
      return this[getter]();
    }
"

What is the correct way to access this name value ? It's not a bug btw, it's just something I'm stuck on !

ok thanks !

**Comment by lavrton** [comment]
You should call it as a function:

`const name = animation.name()`
