### ISSUE TITLE
How to set the pixelRatio of the ScenceCanvas?

### ISSUE THREAD

**Issue by JHOproject** [konvajs/vue-konva#218]
Hi, I want to change the pixelRatio of the ScenceCanvas from 2(default) to 1. But I can't find the method or property to set this. Does anyone have idea?

**Comment by lavrton** [comment]
You can do this once globally with `Konva.pixelRatio = 1`;

Or you can get reference to layer instance and update ratio manually:
```
layer.canvas.setPixelRatio(1);
``
