### ISSUE TITLE
How to set the Points of V-SHAPE

### ISSUE THREAD

**Issue by djkloop** [konvajs/vue-konva#219]
How to set the Points of V-SHAPE?

#### There is such a code in the example of the official website，How to set Points in Vue's Ref?
![image](https://github.com/konvajs/vue-konva/assets/21050914/8e030048-c6b8-4396-9d9c-7ec1054b8e1e)

![image](https://github.com/konvajs/vue-konva/assets/21050914/7c3517ba-8138-4457-b4cd-e3aead5295e6)

**Comment by lavrton** [comment]
What did you try?

You have ts error in the last image, because you set type to `Konva.Shape`. Shape has no `points`. You may want to use `Konva.Line` instead.

**Comment by djkloop** [comment]
@lavrton 
https://konvajs.org/docs/sandbox/Modify_Curves_with_Anchor_Points.html 

I want to use v-shap in vue-konva to draw a Bezier curve, and then I want to change its points when scrolling, just like the example on the official website, but when I use the find method in the ref of v-stage There is no points method on the obtained object

**Comment by djkloop** [comment]
![image](https://github.com/konvajs/vue-konva/assets/21050914/ba36e8ef-8822-400f-98f4-eeb6e1a8a5a1)

![image](https://github.com/konvajs/vue-konva/assets/21050914/47427a7c-9e51-41c2-a97e-24457b273d03)

This is my code, pass the ref stage to the parent in the component, and then get the shape in the parent method, hoping to change its points
