### ISSUE TITLE
`props.config.crop` is not reactive

### ISSUE THREAD

**Issue by TooBug** [konvajs/vue-konva#220]
For example, if I put an image via `<v-image :config="config"></v-image>`, the `config` is like this:

```js
const config = ref({
  x: 100,
  y: 100,
  width: 100,
  height: 100,
  crop: {
    x: 100,
    y: 100,
    width: 100,
    height: 100,
  },
  image: ...,
})
```

If the properties of `crop` changes, nothing happens.

Reason: the code here <https://github.com/konvajs/vue-konva/blob/ffe51b5985553aa6b5ea2911f2ffee3362214a21/src/components/KonvaNode.ts#L79-L83>

didn't deal with sub properties of `props.config`, so the `crop` property of `newProps` and `oldProps` become the same Object (a Proxy Object), then here <https://github.com/konvajs/vue-konva/blob/ffe51b5985553aa6b5ea2911f2ffee3362214a21/src/utils/applyNodeProps.ts#L59-L67>

Since `crop` property of both `props` and `oldProps` are the same, the code treat it as unchanged, so `hasUpdates` would be `false`, nothing happens.

Fix: When composing `newProps`, consider to literal `props.config` and do a deep copy.

What prevents me to send a PR: the source code of master branch are as shown, but in the npm package, it becomes:

```js
        var newProps = KonvaNode_extends({}, attrs, structuredClone(props.config), events);
```

But I can not find the `KonvaNode_extends` method in source code.

**Comment by lavrton** [comment]
Hmm, I am not sure copying of props is a suitable approach. It may drop the performance a lot.

The workaround solution is to use plain version of crop:

```js
const config = ref({
  x: 100,
  y: 100,
  width: 100,
  height: 100,
  cropX: 100,
  cropY: 100,
  cropWidth: 100,
  cropHeight: 100,
  image: ...,
})
```

**Comment by TooBug** [comment]
@lavrton Wow, it works! Thanks for your help. It would be better if the docs have more instructions on this.
