### ISSUE TITLE
How fo Fit the Stage in a responsive way For Mobile Devices

### ISSUE THREAD

**Issue by i-iktear** [konvajs/vue-konva#223]
<img width="1440" alt="image" src="https://github.com/konvajs/vue-konva/assets/26440367/6a98c046-7ccc-4200-9e2c-065894129567">

I have made a seat plan builder using vue konva. but can't shrink the stage for mobile devices to puchase the seat. is there any way? can anyone help?

**Comment by lavrton** [comment]
What is your desired UX? You can just scale it down and implement pinch-to-zoom.
