### ISSUE TITLE
Why is the latest version not released on Git?

### ISSUE THREAD

**Issue by chenzio** [konvajs/vue-konva#225]
![image](https://github.com/konvajs/vue-konva/assets/24283515/fb75656f-af1a-4486-87f0-d9afa269d1c3)

![image](https://github.com/konvajs/vue-konva/assets/24283515/49f31ae1-f624-4753-add1-0d41bd0e8274)

![image](https://github.com/konvajs/vue-konva/assets/24283515/9b09ba01-3d06-4e9f-a218-06251a86ac4a)

**Comment by lavrton** [comment]
It is on git. Looks like just tags are missing.

**Comment by chenzio** [comment]
> It is on git. Looks like just tags are missing.
could you tag it?

**Comment by lavrton** [comment]
Done
