### ISSUE TITLE
Order element after build app is not working correctly.

### ISSUE THREAD

**Issue by ivanglpz** [konvajs/vue-konva#227]
Hello. Good afternoon. I m working with konva and vuejs. vite and i found a "bug" or "problem" after the build.

When i test the shapes for example: Rect, Circle and Group with combined with Arrow.

Screenshot 1 ---- DEVELOPMENT
In mode development works fine. I add elements in order. Im not using zindex, i have a vue state and i add in order.

![Screenshot 2024-01-04 180055](https://github.com/konvajs/vue-konva/assets/67771688/caae9cde-df5e-4d9e-895f-511d3e8e391c)
![Screenshot 2024-01-04 175249](https://github.com/konvajs/vue-konva/assets/67771688/7d092ea9-5aed-4212-a59d-c9bf3fbf79fa)

Screenshot 2 ---- PRODUCTION
If I add the elements rect, circle and arrow in combination with group, the arrow goes to the bottom of the elements or backwards. 
I check if the problem was with the state. but in production it works correctly. 

![Screenshot 2024-01-04 175346](https://github.com/konvajs/vue-konva/assets/67771688/d6c8c211-956e-4a98-a9cc-156d4d4b22a9)

I don't know what configuration is neccesary for works fine :c

Package.json

"vue": "^3.2.45",
 "konva": "^9.3.0",
 "vue-konva": "^3.0.2",

**Comment by lavrton** [comment]
Please provide a very small demo or a repo.

**Comment by ivanglpz** [comment]
I solved it using the setZIndex
