### ISSUE TITLE
v-circle dragmove with v-line error

### ISSUE THREAD

**Issue by Mt-Youya** [konvajs/vue-konva#230]
I transformed the issue [konva issue #1701](https://github.com/konvajs/konva/issues/1701) @lavrton 
I have a issue with drag cirle with vertical line & horizontal line.
I got a intersect point form vertical line and horizontal line. 
I wanna dragmove intersect point anywhere,  at same time two lines got right intersect point, but i got wrong intersect point after  dragmove anyone line 

[code here](https://codesandbox.io/p/devbox/vue-konva-circledragwithline-demo-yz3522?file=%2Fsrc%2FApp.vue%3A45%2C42)

Step1 : dragmove vertical line anywhere 
 ![1705391399960](https://github.com/konvajs/vue-konva/assets/57708498/8bbef3db-12e8-4d56-aac5-4daeb3c1c465)
Step2 : dragmove horizontal line anywhere ![1705391399962](https://github.com/konvajs/vue-konva/assets/57708498/653c9c6b-d43a-4262-8fee-7188386e8edf)
Step3 : dragmove intersect point antwhere ![1705391399966](https://github.com/konvajs/vue-konva/assets/57708498/c9fc87b2-5af0-4b7e-a6dc-573c4dec7dee)
expect:  the  intersect point at right position
result:  the  intersect point at wrongposition

**Comment by lavrton** [comment]
I think you should update it into "vue-way". It means your component should have a state. State is a position of circle. So line will use this position too. On dragging of any node, you should update the state, so it automatically updates other relative shapes.

**Comment by Mt-Youya** [comment]
Sry, i  just have 1 year coding vue experience, i'm learning vue now! So, i dont understand "vue-way"
You means I should be use "reactive" from "vue" , the ref record cirlcle position ,and line tracking the "reactive"?

```js
const circleState = reactive({x:100,y:200})

function handleCircleDragMove(e){
    const that = e.target
    circleState.x = that.x()
    circleState.y = that.y()
}
```

```html
<v-circle :config="circleState"  @dragmove="handleCircleDragMove"/>
<v-line :config="{points:[circleState.x ,0 , circleState.x , 200]}" />
<v-line :config="{points:[0 , circleState.y , 400,circleState.y]}" />
```
Something like this ?
![image](https://github.com/konvajs/vue-konva/assets/57708498/285fc567-332a-4303-a072-d304d5f9c89b)

[code here](https://codesandbox.io/p/devbox/vue-konva-circledragwithline-demo-yz3522?file=%2Fsrc%2FApp.vue%3A18%2C1)

I dragmove circle , but lines dont changes

**Comment by lavrton** [comment]
Yes, that is the approach. Something is not ok with your `SingleLine` component. If I use simple `v-line` instead, it updates correctly.

**Comment by Mt-Youya** [comment]
Hi @lavrton , I use simple `v-line` instead, when i dragmove line , i use `line,position()` get position transformed, and then i updating circleState, circleState will be mutipul plus the  circleState x or y. but  why i got wrong position , how can i calculate final intersect point?
[code here](https://codesandbox.io/p/devbox/vue-konva-circledragwithline-demo-yz3522?file=%2Fsrc%2FApp.vue%3A34%2C44)

**Comment by lavrton** [comment]
It is better not to change `points` of a line on dragging. Dragging is changing position. So you just need to control `x` and `y`.

```js
:config="{
          points: [0, 0, 0, 1000],
          x: circleState.x,
          stroke: '#f00',
          strokeWidth: 5,
          draggable: true,
        }"
```
