### ISSUE TITLE
Non-Konva shape elements inside template

### ISSUE THREAD

**Issue by ExQDev** [konvajs/vue-konva#234]
Hi, sorry for non-standard issue format and content, I don't know is this a bug or not, I've tried to make a "shape" with core logic, but splitted template.
Here it is:
```
<template>
  <v-group>
    <v-image :config="rtconfig" ref="img"></v-image>
    <Teleport to="body">
      <textarea....>
      <div id="rt-container" v-html="content"></div>
    </Teleport>
  </v-group>
</template>
```

That's my final version for this moment.
I supposed, that Konva should ignore tags under the `<Teleport>`, but...:

```
vue-konva error: You are trying to render "textarea" inside your component tree. Looks like it is not a Konva node. You can render only Konva components inside the Stage.
```

Without `<Teleport>` it ignores that and it even cut out from logic.

As was said in guide, I should render rich text to image, and I tried to do this out of component tree. Why it consider that teleported content is rendering to canvas as shape?

Is there a way to split `shape` template with `DOM` template? Or to make Konva ignore `<Teleport>` content?

**Comment by lavrton** [comment]
So `vue-konva` doesn't support `<Teleport />` and I am not sure how to easily enable it.
