### ISSUE TITLE
custom shape with <v-shape/>, mousemove & drag event not working as expected in some area

### ISSUE THREAD

**Issue by litgh** [konvajs/vue-konva#235]
I created a custom shape using v-shape, like a table, The mousemove and drag events for the header and row0 of the table are not working as expected. but <= 2 rows are fine.

<img width="393" alt="image" src="https://github.com/konvajs/vue-konva/assets/7381607/d28841d4-1696-443f-814e-5525cd6c2c3e">

"konva": "9.3.6",
"vue": "^3.4.7",
"vue-konva": "3.0.2"

my code: https://codesandbox.io/p/devbox/stoic-thompson-jwjrhj?file=%2Findex.html%3A11%2C22

**Comment by lavrton** [comment]
IF you do manual filling inside `sceneFunc`, I don't recommend to use `ctx.fillStrokeShape(shape);`. Instead draw everything that you need and fill/stroke/style manually. Then create a separate `hitFunc` just for events/hit detection:

```js
    <v-shape
        :draggable="true"
        :config="{
          x: 0,
          y: 300,
          width: 350,
          height: 150,
          sceneFunc(ctx, shape) {
            ctx.beginPath();
            ctx.fillStyle = 'red';
            ctx.rect(0, 0, minTableWidth, rowHeight);
            ctx.fill();
            ctx.closePath();
            let y = rowHeight;
            for (var i = 0; i < 2; i++) {
              ctx.beginPath();
              ctx.fillStyle = rowColor;
              ctx.rect(0, y, minTableWidth, rowHeight);
              ctx.fill();
              ctx.closePath();
              ctx.fillStyle = 'black';
              ctx.textAlign = 'left';
              ctx.fillText('Row' + i, cellPadding, y + rowHeight - cellPadding);
              y += rowHeight;
            }
           // ctx.fillStrokeShape(shape);
          },
          hitFunc(ctx, shape) {
            ctx.beginPath();
            ctx.rect(0, 0, minTableWidth, rowHeight);
            ctx.fillStrokeShape(shape);
          },
        }"
      />
```

**Comment by litgh** [comment]
Thank you for your reply, it solved the problem that puzzled me all day.
