### ISSUE TITLE
How to implement Transformer custom icon？

### ISSUE THREAD

**Issue by Jonas949** [konvajs/vue-konva#238]
I want to achieve the effect shown in the image below and add a rotating icon at the top of it so that the user can clearly see what it is used for and how should I do it?
![1716532520591](https://github.com/konvajs/vue-konva/assets/54925213/ad6c7317-8016-4818-ae40-7f25b1d26a6a)

**Comment by lavrton** [comment]
https://konvajs.org/docs/select_and_transform/Transformer_Complex_Styling.html#title-Deep-Style-Konva-Transformer
https://vanquishedwombat.ghost.io/konva-styling-transformer-anchors/
