### ISSUE TITLE
Declaration type not being exported

### ISSUE THREAD

**Issue by aoor9** [konvajs/vue-konva#243]
Types cannot be detected because the `dist` folder doesn't include/generate the `index.d.ts` file.

Package versions :
Vue-konva : 3.0.5

**Comment by lavrton** [comment]
Added, I am not sure yet if it will help much

**Comment by Joebayld** [comment]
> Added, I am not sure yet if it will help much

@lavrton I think this might have broken the library. Please look at this issue. https://github.com/konvajs/vue-konva/issues/244

I cannot get this library to work anymore as there are no types.
