### ISSUE TITLE
Types are missing

### ISSUE THREAD

**Issue by Joebayld** [konvajs/vue-konva#244]
I was on version 3.0.2 and when I tried upgrading to either 3.0.5 or 3.1, I now have an error that the types are not found. 

<img width="494" alt="Screenshot 2024-08-13 at 2 44 30 PM" src="https://github.com/user-attachments/assets/d0b6287f-3a20-4d8c-b19a-5ce71673444f">

If I downgrade back to 3.0.2 it's fine.

**Comment by Avarow** [comment]
Doesn't help, issue is still present

**Comment by Joebayld** [comment]
> Doesn't help, issue is still present

I don't think there was any suggested fix? I just quoted what broke it. Looks like this copy script is overwriting the generated types.

**Comment by Avarow** [comment]
Oh, thought @lavrton tried a fix on https://github.com/konvajs/vue-konva/issues/243

**Comment by Joebayld** [comment]
I get the feeling not many people use typescript with this because it's very broken right now

**Comment by Joebayld** [comment]
@lavrton can you please look into this. It appears the new build script `cp ./index.d.ts ./dist/index.d.ts` is overwriting the types that the module is already building.

**Comment by lavrton** [comment]
I just added generated types and released a new version. I need feedback whether it works or not.

**Comment by Joebayld** [comment]
Just tested it. Still no luck - but I think I found the fix. 

I'm not sure what `types.d.ts` is, but if you change the package.json to use `vue-konva.d.ts` it fixes it. See screenshot: 

<img width="479" alt="Screenshot 2024-09-16 at 3 29 38 PM" src="https://github.com/user-attachments/assets/42365f84-d56b-440d-81ca-384ee8ca2bf8">

**Comment by lavrton** [comment]
@Joebayld what about now with v 3.1.2?

**Comment by Joebayld** [comment]
@lavrton Fixed! thanks

**Comment by odetolakehinde** [comment]
I have this same issue with nuxt 3 when I do this:

```
import * as VueKonva from 'vue-konva';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueKonva)
})
```

error:
```
Argument type
{   readonly default: {     install: (app: any, options?: {       prefix?: string,       customNodes?: Record<string, KonvaNodeConstructor>     }) => void   } }
is not assignable to parameter type  Plugin<unknown[]>    Assigned type doesn't contain call signatures 
```
in `node_modules/vue-konva/dist/index.d.ts`

**Comment by lavrton** [comment]
@odetolakehinde Please make a separate issue with a very small repository to reproduce the issue.
