### ISSUE TITLE
[Proposal] vue-konva v2

### ISSUE THREAD

**Issue by lavrton** [konvajs/vue-konva#25]
Hello, everyone. I am going to work with a new version of `vue-konva` and make many changes in repo structure and some code behavior:

- [x] Get rid of all webpack and other configuration from the repo. Instead, start using https://github.com/insin/nwb so we don't need to care about configurations.
- [x] Add tests to cover mosts of the cases
- [x] Create many demos/tutorials and add them into https://konvajs.github.io/docs/vue/ section
- [x] Possibly change events behaviour. Currently event handlers has `VueComponent` as the first argument. I think it will be better to have event object as the first argument instead.
- [ ] Can we avoid usage `config` propery and define attributes directly? Like this: `<v-rect fill="red"/>`

**Comment by rafaesc** [comment]
Hi there,

`VueComponent` do you propose to add in the second param?

Another approach is to develop a method to access to component sending the event as param.

maybe like this
http://www.chartjs.org/docs/latest/developers/api.html#getelementatevente

**Comment by lavrton** [comment]
I don't think it is required as the second parameter. Because the scope of the function already bound to the current component. 

That is the simple test I created. All works just fine:

```javascript
    const { vm } = mount({
      template: `
        <v-stage ref="stage" :config="size">
          <v-layer ref="layer">
            <v-rect ref="rect" @mousedown="mousedown" :config="size">
            </v-rect>
          </v-layer>
        </v-stage>
      `,
      data() {
        return {
          size: {
            width: 100,
            height: 100
          }
        };
      },
      methods: {
        mousedown(e) {
          expect(this).to.equal(vm);
          expect(e.target instanceof Konva.Rect).to.equal(true);
        }
      }
    });

    const stage = vm.$refs.stage.getNode();

    stage.simulateMouseDown({
      x: 50,
      y: 50
    });
```

**Comment by lavrton** [comment]
Just made a release of version `2.0.0` and added many demos to https://konvajs.github.io/docs/vue/
