### ISSUE TITLE
how to make stage responsive?

### ISSUE THREAD

**Issue by xulei890817** [konvajs/vue-konva#27]
[https://konvajs.github.io/docs/sandbox/Responsive_Canvas.html](https://konvajs.github.io/docs/sandbox/Responsive_Canvas.html)
 
this is my code 
```javascript
computed: {
    stage() {
      return this.$refs.stage.getStage();
    },
  },
```

```javascript
      const scale = 2;
      this.stage.width = this.stage.width * scale;
      this.stage.height = this.stage.height * scale;
      this.stage.scale({ x: scale, y: scale });
      this.configCircle.x = this.configCircle.x - 50;
      this.stage.draw();
```

the stage size is not changing,the canvas size seems can't be changed by this way,but i can see the circle   scale 2x bigger.

![image](https://user-images.githubusercontent.com/5419347/49072383-0c80f300-f26b-11e8-84b1-d371ae7b5e70.png)

i see your componet, it has two div outside the canvas,it seems must  set spectified width and hieght.

**Comment by lavrton** [comment]
It is better not to change nodes properties directly. Save them somewhere in `data` and then use it `render` or `template`.

And `stage.width` is a function. So you need to do this `stage.width(newValue)`.

**Comment by callumvh** [comment]
Hi, did you find a solution with code by any chance?

**Comment by xulei890817** [comment]
> Hi, did you find a solution with code by any chance?

just as lavrton said,  while the width changed,  use stage.width(newValue) will be ok
this is my new code 
```javascript
window.addEventListener('resize', this.changeRect);
```

the main code in changeRect
```javascript
      const height = this.container.offsetHeight;
      const width = this.container.offsetWidth;
      this.configKonva.width = width;
      this.configKonva.height = height;
      this.stage.width(this.configKonva.width);
      this.stage.height(this.configKonva.height);
```

**Comment by callumvh** [comment]
Thanks, could you possibly share the template section if you don't mind as I'm still having trouble getting it to work.

Sorry I'm quite new to vue.js/konva and I'm not sure how you declared the "this.container", is it just a div like in the responsive demo or something like "<v-container>"?

Any help is greatly appreciated.

**Comment by lavrton** [comment]
@callumvh take a look here: https://codesandbox.io/s/502p384jyp

**Comment by callumvh** [comment]
Hi, I noticed that in the demo you sent me, it only works with the vertical window size change, not the horizontal.

So if you change the width of the window, it changes as you resize.

If you resize the height, you need to refresh the page to get it to resize.

I tried it in my own app and the same thing happens.

**Comment by lavrton** [comment]
Sure. My you just need to set CSS values to fit the required size. Updated the demo: https://codesandbox.io/s/502p384jyp

```
<template>
  <div v-bind:style="{ height: '100vh', width: '100vw' }" ref="container">
    <v-stage ref="stage" :config="stageSize">
      <v-layer>
        <v-circle
          :config="{
            x: 50,
            y: 50,
            radius: 50,
            fill: 'green'
          }"
        />
        <v-circle
          :config="{
            x: stageSize.width - 50,
            y: 50,
            radius: 50,
            fill: 'green'
          }"
        />
        <v-circle
          :config="{
            x: stageSize.width - 50,
            y: stageSize.height - 50,
            radius: 50,
            fill: 'green'
          }"
        />
        <v-circle
          :config="{
            x: 50,
            y: stageSize.height - 50,
            radius: 50,
            fill: 'green'
          }"
        />
      </v-layer>
      <v-layer ref="dragLayer"></v-layer>
    </v-stage>
  </div>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;
let vm = {};
export default {
  data() {
    return {
      stageSize: {
        width: width,
        height: height
      }
    };
  },
  created: function() {
    window.addEventListener("resize", this.changeRect);
    this.changeRect();
  },
  methods: {
    changeRect: function() {
      const container = this.$refs.container;

      if (!container) {
        return;
      }

      const height = container.offsetHeight;
      const width = container.offsetWidth;

      console.log(height, height);
      this.stageSize.width = width;
      this.stageSize.height = height;
    }
  }
};
</script>
```

**Comment by JohnLis** [comment]
Hi @lavrton,
Is it possible to set custom with and height of canvas layers? Those canvases are not the same as stage.
![Screenshot_7](https://user-images.githubusercontent.com/17541674/123837207-dd432e80-d90a-11eb-9e07-0a99e6e4bf02.png)
I put video in konvajs and apply filters to it. But computing every pixel of canvas slows down application. Is there any solution?

**Comment by lavrton** [comment]
Konva is doing automatic adjustments for HDPI screens (like retina). It is required for sharp and good display. You can read more about it here: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

If you don't need it, you can manually change that behavior:

```js
Konva.pixelRatio = 1;
```
