### ISSUE TITLE
Node with multiple colors

### ISSUE THREAD

**Issue by ninjami-mohammed** [konvajs/vue-konva#31]
I made a shape by using circle and arrow nodes, the arrow start points are the same for the circle, The circle has an transparent color that makes the arrow visible under the circle, My goal is that I want the arrow to start from the circle's edge.
I tried to find a solution using the offset and I tried to find a way to change a color of between specific points on the arrow stroke so I can put it transparent color for that visible part but I couldn't.
(Please check the image)
<img width="194" alt="screenshot 2018-12-21 at 16 25 34" src="https://user-images.githubusercontent.com/42730759/50347665-023ad780-053f-11e9-98f4-c7df10e36047.png">

I wish that you can help me with that.

Thanks in advance.

**Comment by lavrton** [comment]
> My goal is that I want the arrow to start from the circle's edge

So just do it. Calculate edge position and start arrow from that point. Do you know how to do that?

There is no way to change colors between points in `Konva.Arrow`.

**Comment by ninjami-mohammed** [comment]
Hi Anton

Thank you for reply, I tried that before but the issue was that the circle
offset point ( Center of the circle ) should be the start point of the
arrow, because the circle is dragable and arrow start point should follow
it, Please if you can show me how to calculate it I will appreciate that so
much.

Thank you again

**Comment by lavrton** [comment]
Just use the power of trigonometry to calculate offset from circles centers. Like this:

```javascript
const OFFSET = 15;

// p1, p2 are centers of circles
function getPoints(p1, p2) {
  var deltaX = p1.x - p2.x;
  var deltaY = p1.y - p2.y;
  var rad = Math.atan2(deltaY, deltaX);
 
  
  return [
    {
      x: p1.x + OFFSET * Math.cos(rad+ Math.PI),
      y: p1.y + OFFSET * Math.sin(rad+ Math.PI),
    },
    {
      x: p2.x + OFFSET * Math.cos(rad),
      y: p2.y + OFFSET * Math.sin(rad),
    }
  ]
}
```

Demo https://jsbin.com/coxesuxano/1/edit?html,js,output   (try to drag a circle)
