### ISSUE TITLE
ZIndexing - SetZIndex(value)

### ISSUE THREAD

**Issue by deathblade89** [konvajs/vue-konva#32]
Hi Konva,

Once again thank you for this incredible library.

I have a demo where i am trying to adjust the z-index of nodes.

https://codepen.io/anon/pen/KbeGaM

The z-indexing i have tried to do is on the group and or the rects in the demo.

I cannot seem to get the Groups to move up or down or the rects to move up or down.

Could you please assist.

**Comment by lavrton** [comment]
`zIndex` is relative to parent element only. `zIndex` is just index of a node in children of its parent.

So, this line `rect1.setZIndex(2);` will not work. Because `react1` can have only `zIndex = 0` because it is only one child of the `group1`.

You may want to use this:

```javascript
group1.setZIndex(1);
group2.setZIndex(0);
// actialy the last line is not required. Because it will be already at index = 0
// after moving group1 
```
