### ISSUE TITLE
Resize text area without scaling the text itself

### ISSUE THREAD

**Issue by mdeprezzo** [konvajs/vue-konva#33]
Hi guys,
it's possible to resize the container of the text, without distort the text itself ?

Something like that:

[Example](http://104.237.3.144/BookMaker/book.html)

**Comment by lavrton** [comment]
Do you need this: https://jsbin.com/jocovugewa/edit?html,js,output?

**Comment by mdeprezzo** [comment]
@lavrton exactly. Thanks! This library is amazing!
