### ISSUE TITLE
Issues with moveUp and moveDown when trying to create an interface to move images

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/vue-konva#34]
I have created the following example https://codesandbox.io/s/kxj7rxqo4v because the issue is quite hard to explain.

Basically what I am trying to create is an interface where users can see a list of all the images in a layer in the order (based on z-index) they appear in.

I then want to have buttons to allow them to 'raise' or 'lower' an image (using `moveUp` or `moveDown`)

So far I can get the images moving down but as soon as you click back on the canvas the moved down image re-appears, I think this is to do with caching but I can't quite figure out how it is supposed to work.

Additionally I can't quite get the buttons to work, the initial move down will work but if you then try to move the new top element (assuming you have only uploaded 2 images) (which is now effectively one layer higher because it has had a layer moved below it it will not work) you can see this if you click around on the buttons in the demo.

Any insight would be much appreciated!

Cheers!

**Comment by lavrton** [comment]
`vue-konva` will always try to keep nodes in order, as you defined them in `template`. So you don't need to use `moveUp` and `moveDown` methods manually. If you move nodes manually, `vue-konva` may reset them back. Just set correct order in your `data`. Like this:

```javascript
    moveImageUp(index) {
      // cut
      const image = this.images[index];
      this.images.splice(index, 1);
      this.images.push(image);
      
      // vue-konva should update layer automatically, but somehow
      // it din't, so we will do it manually
      // probably it is a bug in vue-konva
      const stage = this.$refs.stage.getStage().draw();
      this.setImageIndexes();
    },
```

https://codesandbox.io/s/k3nv5o9xx5

**Comment by CrashyBang** [comment]
Just want to note this down I found a really weird edge case not sure if it is a bug with `vue`, `vue-konva`, or `konva`.

I have an example here: https://codesandbox.io/s/ppkl75mq3q you will notice if you re-order the images (using the up and down buttons) after you have dragged them the re-order stops working and then when you click on the canvas everything moves.

Here I have the exact same code https://codesandbox.io/s/y3y9nvk13x the only exception being that where I iterate the over the `images` array we are using `:key="image.src"` instead of `:key="index"` which entirely resolves the issues, I can re-order and drag and re-order etc... and nothing breaks.

Any idea what this would be...?

Cheers.

**Comment by lavrton** [comment]
Just learn more about "key" property and best practices for it. *Hint*: using an index as `key` is a bad approach in many cases.
