### ISSUE TITLE
The sample in readme (without webpack) isn't working

### ISSUE THREAD

**Issue by paulvanbladel** [konvajs/vue-konva#36]
I need a version of vue-konva on a page without webpack but with vue.
I tried the sample from the readme but that fails.
I cloned the sample over here, so you can take a look if you want:
https://github.com/paulvanbladel/vue-konva-no-webpack

The readme sample has a small type since it refers to a .min file, but even when solving that it fails.
Any idea?
thanks a lot.

**Comment by lavrton** [comment]
Just added a build and published a new version.

See updated README or demo: https://jsbin.com/nalovavoqa/2/edit?html,js,output
