### ISSUE TITLE
Question about grouping

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/vue-konva#37]
I want to allow users to select a group of nodes so that they can resize/rotate/etc...

I know that I want something like [this](https://jsbin.com/lurakakuva/2/edit?js,output) in terms of setting up the transformer.

What I am having trouble with is that my nodes are spread across layers, my structure looks something like this.

```
<v-stage>
    <v-layer ref="imageLayer">
        <!-- nodes... -->
    </v-layer>
    <v-layer ref="shapeLayer">
        <!-- nodes... -->
    </v-layer>
    <v-layer ref="textLayer">
        <!-- nodes... -->
    </v-layer>
    <v-layer ref="groupLayer">
        <v-group></v-group>
    </v-layer>
</v-stage>
```

Where I want to be able to select nodes from the first three layers, add them to the `v-group` resize/rotate/etc... them and then put them back in their respective layer, is this the right way to approach this problem?

Cheers.

**Comment by lavrton** [comment]
So try to move them to the group, then move back to original layers. Did you try that?

**Comment by CrashyBang** [comment]
Hey @lavrton,

That was my thinking I was simply asking if this is the best approach, or if some other functionality existed.

Cheers.

**Comment by lavrton** [comment]
I guess the question is resolved.
