### ISSUE TITLE
Layer children is not updated after using destroy on a node

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/vue-konva#38]
I have created an example here: https://codesandbox.io/s/oq3p2y8lzq

Basically when I call destroy on a node, that node is still in the `$children` array of the layer.

It appears to break `getAbsoluteZIndex()` on other nodes, it throws:
```
Cannot read property 'getChildren' of undefined
```
**EDIT**
After thinking about this a bit more I actually need to be removing the item from the array the nodes are generated from, i.e I am currently iterating over an `images` array to generate the images:
```
<v-image
	v-for="image in images"
	:key="image.src"
	:config="{
            image: image,
            draggable: true,
       }"
/>
```

Is there anyway from the node instance (`getNode()`) to identify which item it is on the original array so I can remove it?

**Comment by lavrton** [comment]
Removing item from the array is the correct way. Do not remove nodes manually.

You can set an index as a custom attribute or use a specific name.

```
<v-image
  v-for="(image, index) in images"
  :key="image.src"
  :config="{
            index: index,
            image: image,
            draggable: true,
  }"
/>
```

Then in you methods:

```javascript
handleClick(e) {
      const index = e.target.getAttr('index');
      this.texts.splice(index, 1);
}
```

https://codesandbox.io/s/vj54wlr0k0
