### ISSUE TITLE
window.Konva is undefined with Konva version 3.1.2

### ISSUE THREAD

**Issue by ericssan** [konvajs/vue-konva#39]
Looks like with recent version of Konva - 3.1.2 window.Konva is undefined.
Thus it results in error in mounted hook in `vue-konva.js`:
`"TypeError: Cannot read property 'Stage' of undefined"`
```js
  mounted: function mounted() {
    this._stage = new window.Konva.Stage({
      width: this.config.width,
      height: this.config.height,
      container: this.$el
    });
    this.StageEmitter.emit('mounted', this._stage);
    this.uploadKonva();
  },
```
[Here is a link to codesandbox to reproduce problem](https://codesandbox.io/s/8l8j253mo2)

One can get around this problem with a hack like:
```js
if (!window.Konva) window.Konva = require('konva');
```

**Comment by lavrton** [comment]
Fixed with the new version. Thanks for the report.
