### ISSUE TITLE
Adding event modifiers

### ISSUE THREAD

**Issue by cyan0n** [konvajs/vue-konva#4]
It seems that [Event Modifiers](https://vuejs.org/v2/guide/events.html#Event-Modifiers) aren't implemented in the current package.
Is it possibile to use these Event Modifiers on the vue-konva components?

I've tried using _@mousedown.left_, but it doesn't seem to trigger the event.

**Comment by rafaesc** [comment]
Hi @cyan0n,

but in the vue documentation, the event modifier `left` doesn't existed.

Regards

**Comment by cyan0n** [comment]
It also works with mouse events https://vuejs.org/v2/guide/events.html#Mouse-Button-Modifiers

**Comment by cyan0n** [comment]
Also noted that the _contextmenu_ event isn't working either.
And just to clarify, I have tested these events in other Components making sure that they work is basic vue components

**Comment by rafaesc** [comment]
yes, its because the first param that the event function return its the vue component, so, it's necessary that the first param will be the event to can be filter it.

**Comment by rafaesc** [comment]
Hi @cyan0n,

I tried to support the event modifiers, but if I want that works, I need that the event only had one parameter it would be the mouse event.

```js
instance.on(eventName, evt => {
  const konvaEvent = evt;
  const mouseEvent = evt.evt;
  props[key](mouseEvent);
});
```

So it seems that there isn't a way to send the konva event or the vue component, and that is important to change the behaviour of konva element or manipulate the vue components.

https://github.com/rafaesc/vue-konva/blob/master/src/utils/applyNodeProps.js#L45

**Comment by rafaesc** [comment]
For version 1.0.6

Event modifiers are supported for [Stage Events](https://konvajs.github.io/docs/events/Stage_Events.html)

You can see an example here https://github.com/rafaesc/vue-konva/blob/master/examples/components/Circle.vue
[demo on live](http://rafaelescala.com/vue-konva/#/circle)

Regards

**Comment by lavrton** [comment]
As I can see event modifiers works just fine with the last version: https://codesandbox.io/s/vue-konva-event-modifiers-demo-i4u92
