### ISSUE TITLE
Stage drawing shapes often don't work.

### ISSUE THREAD

**Issue by fangyanli** [konvajs/vue-konva#41]
Hi there,

I have a puzzle about konva's use in IOS 12.1.1.
"konva": "^2.6.0","vue": "^2.5.2","vue-konva": "^2.0.2";

When I switch a component with konva through routing jumps, 
I often fail to draw graphics.

I don't know if this problem has happened on your side,
and if there are any solutions or suggestions. 

Thanks for your help!

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by fangyanli** [comment]
Demo has, but the external network can not be accessed, I want to find an external network server, wait for me one day, thank you.thank you.thank you .

**Comment by fangyanli** [comment]
![Uploading 4.png…]()
![Uploading 5.png…]()
![Uploading 6.png…]()
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by fangyanli** [comment]
hi，
I'm sorry, demo example can't be uploaded.sorry！

**Comment by fangyanli** [comment]
Hi there,
This is the demo address. http://screenmate.cn/
You can try it on iPad IOS 12.1.1。
Thank you in advance.

**Comment by lavrton** [comment]
I checked the app and I saw the issue. It is a memory usage issue. Make sure you use small canvases on mobile devices. Also, reduce the number of layers. And you can use this `Konva.pixelRatio = 1`.

**Comment by fangyanli** [comment]
Thank you. I'll try. Looking forward to solving the problem.

**Comment by fangyanli** [comment]
It's a little better.but there's still a problem.
We should only continue to find out if there is any other way.

**Comment by lavrton** [comment]
Make a demo, so I can take a look.

**Comment by fangyanli** [comment]
This is the demo address. http://screenmate.cn/

**Comment by fangyanli** [comment]
https://github.com/fangyanli/konvaDemo
https://github.com/fangyanli/konvaDemo.git

**Comment by Dean-Christian-Armada** [comment]
> I checked the app and I saw the issue. It is a memory usage issue. Make sure you use small canvases on mobile devices. Also, reduce the number of layers. And you can use this `Konva.pixelRatio = 1`.

May I know how to set this in `Vue`?

I tried

```
<v-stage :config="{height:1138, pixelRatio:3, width:375}">
</v-stage>
```

But I am not sure if it worked
