### ISSUE TITLE
Update element state on transform

### ISSUE THREAD

**Issue by vkaracic** [konvajs/vue-konva#42]
Hello!

I have a component with which I can create a new circle by pressing a button to create it. What it does is copies a new attributes object and saves it in the store:
```
{
    id: 1,
    radius: 20,
    fill: 'blue',
    stroke: 'black',
    strokeWidth: 1,
    x: 100,
    y: 100,
    draggable: true,
    offsetX: 0,
    offsetY: 0,
    rotation: 0,
    scaleX: 1,
    scaleY: 1,
    skewX: 0,
    skewY: 0
}
```

And I have a stage component which iterates over those objects saved in the store and creates new `<v-circle>` shapes with those attributes passed in the `config` prop of each shape:
```
<v-stage>
    <v-layer>
        <v-circle
            for="shape in storeShapes"
            :key="shape.id"
            :config="shape"
        />
    </v-layer>
</v-stage>
```
This works fine, but the problem is when I transform the element the attributes in the store stay the same, while the attributes of the Konva node are different, specifically the `scale[X/Y]` attributes.

So my question is, is it possible to keep the shape attributes in the store so that the transformer updates them automatically, or do I have to update them manually when events such as `dragend` and `transformend` are triggered?

I'm storing the attributes in the store in order to manipulate them more easily and for saving and loading of the canvases later on.

**Comment by lavrton** [comment]
You have to save them manually. You are right, you can use `dragend` and `transformend` for that.

**Comment by vkaracic** [comment]
Thanks for the quick reply! :+1:
