### ISSUE TITLE
Using layer.add()

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/vue-konva#43]
I am trying to add nodes to layers with the following code:

```js
textLayer.add(...layers.textLayer);
```

Where `layers.textLayer` is an array of objects like so:

```js
{
    attrs: {
        fill: "rgba(255, 0, 0, 1)",
        index: 0,
        draggable: true,
        text: "Example Text",
        fontFamily: "Bangers",
        fontSize: 60,
        x: 222.41379310344828,
        y: 268.9655172413793,
        scaleX: 4.43772935901027,
        scaleY: 4.43772935901027
    },
    className: "Text",
    filters: []
},
{
    //...
}
```

But I am receiving this error:
```
"TypeError: child.getParent is not a function"
```

I found [this issue](https://github.com/konvajs/react-konva/issues/252) for `react-konva` but I am not sure this is the same issue I am facing with Vue.

**Comment by lavrton** [comment]
If you are using `vue-konva` you don't need to add nodes manually. Just generate them in your `template` from the state of the app.

Please make a demo for your issue. Looks like `layers.textLayer` is not a `Konva.Node` instance.

**Comment by CrashyBang** [comment]
Hey @lavrton,

Yep had just had an idiot moment, just needed to add the objects to the respective array each layer uses to render it's children.

Cheers!
