### ISSUE TITLE
`v-if` may produce zIndex warning into console

### ISSUE THREAD

**Issue by lavrton** [konvajs/vue-konva#45]
Demo: https://codesandbox.io/s/qy176jn4w

**Comment by ralphschindler** [comment]
I've run into a similar situation, any ideas?

**Comment by ralphschindler** [comment]
My situation is that if I have (vue template):

```html
        <v-stage ref="stage" :config="configKonva" @dblclick="doubleClick" @mousedown="mousedown" style="border: 1px solid black">
            <v-layer ref="rectangleLayer">
                <v-rect v-for="(rectangle, index) in rectangles" :key="rectangle.name" :config="rectangle" />
                <v-transformer ref="transformer" :config="{rotateEnabled: false}" />
            </v-layer>
        </v-stage>
```

and then later attempt to:

```js
                const rectangle = {
                    name: 'rect-' + (index + 1),
                    x: mousePos.x,
                    y: mousePos.y,
                    width: 100,
                    height: 100,
                    fill: 'red',
                    draggable: true
                }

                this.rectangles.push(rectangle)
```

I get a warning b/c the Vue canvas looks like this:

![vue-konva](https://user-images.githubusercontent.com/76674/54700356-de1c7180-4b00-11e9-8d74-25527b9f0a98.png)

Adding my own zIndex seems to be an anti-pattern, but clearly the zIndex is not going to match the number of v-rect's in the loop.

**Comment by codenamezjames** [comment]
I'm experiencing this also `<v-transformer ref="transformer" :config="{ keepRatio: metaKey }" />` with this code if i remove the metaKey and use a boolean it doesnt complane

**Comment by zkobrinsky** [comment]
Wait, so what's the solution here?
