### ISSUE TITLE
Stage drawing shapes often don't work on  in IOS 12.1.1.

### ISSUE THREAD

**Issue by fangyanli** [konvajs/vue-konva#49]
Hi there,

I have a puzzle about konva's。
This is the demo address. http://screenmate.cn/
You can try it on iPad IOS 12.1.1。

This is the demo the code address
.https://github.com/fangyanli/konvaDemo
https://github.com/fangyanli/konvaDemo.git

if there are any solutions or suggestions.I will be grateful.

Thanks for your help!

**Comment by lavrton** [comment]
The demo address is not working now. I tried to run `vue` demos from Konva website on the iPhone. They work ok. I will close the issue for now. If you have more information - just add a comment.
