### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by davidm-public** [konvajs/vue-konva#5]
firstly, thanks for an awesome toolkit!
question: how to apply performance tips:
https://konvajs.github.io/docs/performance/All_Performance_Tips.html

e.g. in the case where interactivity not needed.

Dave

**Comment by Ldoppea** [comment]
Hi,

In the case where interactivity not needed, you can add `listening: false` to your `:config`

If you want to access a KonvaNode's method, you can use `getStage()` on the VueKonva object.
The following example should work (but I did not try it) :
```
<v-layer ref="myLayer">

...

someMethod() {
  let layer = this.$refs.myLayer.getStage() // layer = the node related to the v-layer
  layer.hitGraphEnabled(false)
}
```

**Comment by davidm-public** [comment]
<v-fastlayer> seems to increase the performance roughly 2x.
