### ISSUE TITLE
render: createElement( issues

### ISSUE THREAD

**Issue by joantune** [konvajs/vue-konva#50]
Hi!

So - I did a custom component - which tries to spawn Konva-vue components within its render element - by doing calls like `createElement(VueKonva.Text` - the issue is with the fact that such an element won't have a `name` as it won't have a `'componentTag'` - so - I replaced the following line:
`this.name = this.$options._componentTag;`
with:
`this.name = this.$options._componentTag || this.$options.propsData.config.name;`

and added:

the `name` to the props\config - I'm rather new both at Vue and Konva - and I  wonder if this is the way to go to be able to make custom (i.e. with a render method) components that have sub-components with `vue-konva`.

If it is - this 'hack' can be easily added to the docs on a new simple section - I can do a PR on that and on the code

**Comment by lavrton** [comment]
Can you make a demo? What exact issue do you have?

**Comment by lavrton** [comment]
Closing as not enough info.
