### ISSUE TITLE
Red error in console when canvas is empty

### ISSUE THREAD

**Issue by ashleymoogle** [konvajs/vue-konva#51]
Hello, i'm having a ton of errors when i'm creating my canvas with nothing inside
```js
Error in updated hook: "TypeError: Cannot read property 'getZIndex' of null"

found in

---> <VGroup>
...
```

My template is like so
```vue
<v-stage ref="stage" class="canvas" :config="configKonva">
 <v-layer ref="layer">
  <v-group :key="mainStage">
   <BlockContainer />
   <TriggerContainer />
   <CurveContainer />
  </v-group>
 </v-layer>
</v-stage>
```
Any ideas? It's not blocking the execution but I have a ton of these messages in red in the console

**Comment by lavrton** [comment]
Can you make a small online demo with codesandbox?

**Comment by lavrton** [comment]
Closing as not enough info.

**Comment by rebinnaf** [comment]
It's happening when you use a nonKonva component inside the v-layer. If you remove those components the error will disappear. I am not sure if vue-konva supposed to support that case.

take a look at test layer:
https://codesandbox.io/s/practical-ishizaka-bsyvo?file=/src/App.vue

**Comment by lavrton** [comment]
I see. Thanks for the demo. Such a use case is not supported. You can use only konva components. 

I am going to add a better warning message.

**Comment by lavrton** [comment]
Fixed in the last version with a better error message.

```
index.js:27 vue-konva error: You are trying to render "test-counter" inside your component tree. Looks like it is not a Konva node. You can render only Konva components inside the Stage.
```

**Comment by LaureanoBlonsky** [comment]
Hi @lavrton how can I stop getting this error on the console? I use custom components but that are Konva components on the inside. 

Like this one:
`<template>
  <v-rect
    ref="collRect"
    :config="{
      ...data,
      opacity: 1,
      stroke: stroke
    }"
  />
</template>`

Works fine but I want to stop getting the error on the console. Thanks!

**Comment by lavrton** [comment]
Can you make a demo? Our warning should work only for non-konva components.

**Comment by LaureanoBlonsky** [comment]
Sorry for the late response @lavrton !

The example I gave you was incomplete, really. This is the thing: I dynamically load different components depending on data.

For that, I created this _DynamicElement_ component:
`<template>
  <component
    ref="component"
    :is="component"
    :data="data"
    v-bind="$attrs"
    v-if="component"
    v-on="$listeners"
  />
</template>`

And sometimes the component generated has inside another one.

It works great and perfectly, BUT i get the errors on the console, because Konva thinks that the component isnt a Konva component, and its true in some sense, but in this case its a false alarm, because ultimately it always is, and it indeed works great.

The error: **"vue-konva error: You are trying to render "dynamic-element" inside your component tree. Looks like it is not a Konva node. You can render only Konva components inside the Stage."**

What can I do to get rid of the error? Thanks!!!!!!

**Comment by LaureanoBlonsky** [comment]
@lavrton nono, what I meant was that _DynamicElement_ has ALWAYS a Konva component inside. But sometimes, it has a _v-group_ for example, with an _v-image_ and another _DynamicElement_ that renders another Konva component.

For example, My log has this error:
**vue-konva error: You are trying to render "CvCollider" inside your component tree. Looks like it is not a Konva node. You can render only Konva components inside the Stage.**

_CvCollider_ is this:
```
<template>
  <dynamic-element
    ref="collider"
    :data="{
      ...data
    }"
    :id="id"
    :position="position"
    :type="'./CanvasElements/CvCollider' + data.type"
    v-bind="$attrs"
    @updateColliding="updateColliding"
  />
</template>
```
So... yeah, its not A Konva component, but that dynamicElement is finally rendering a Konva component, and NEVER renders other things. So I suppose the library checks if the child is a pure Konva component, and if not, it complains.

Works, but the errors shouldn't be there. What can we do??
And again, thanks!!!!! :)

**Comment by lavrton** [comment]
I think in that case our check is not working correctly. If at the end `<dynamic-element />` is rendering a Konva node, then you should see that warning. 

The idea of the warning is to prevent some unexpected usage, when you are trying to add DOM nodes instead of Konva nodes.

Can you make a demo with such `<dynamic-element />`?

**Comment by LaureanoBlonsky** [comment]
Hi man, I tried... but I get an error that prevent it from working... I cant get it working in a CodeSandbox...
I leave it here if it helps somebody that is facing the same issue: https://codesandbox.io/s/vuejs-compile-string-dfhv5
But it doesnt serves as demo... so I will let the errors stay on logs :(

**Comment by lavrton** [comment]
Looks like it is because your components are async. So while loading `vue-konva` can't detect underlying Konva node. I need to think about how to resolve it.

**Comment by greglaw** [comment]
I'm also running into this error- my konva sub template is not async, however. 
Basically, I have a sub-template that returns a konva element. I want to use it inside many different parent konva element templates. However, despite returning only a <v-group> and it's children, I get the same error warning "vue-konva error: You are trying to render "RemoveNodeFromSelectionIcon" inside your component tree. Looks like it is not a Konva node. You can render only Konva components inside the Stage" 

Although it is indeed a konva node. Oddly enough it still renders fine - it just throws a console error. 

Just figured I'd post here to see if there is anything that can be done to suppress these errors. 
Thanks!

**Comment by lavrton** [comment]
Can you make a small demo?

**Comment by greglaw** [comment]
Sure thing - 
https://codesandbox.io/s/vuejs-compile-string-fouu1 
So in this, if you click the grey circle it enters and exits the red circle (ChildCircleTemplate.vue). Even though the red circle template is purely Konva elements, it seems to throw the 

`vue-konva error: You are trying to render "ChildCircleTemplate" inside your component tree. Looks like it is not a Konva node. You can render only Konva components inside the Stage.`

Error - interestingly, it seems to throw this error when the element leaves the stage, not when it enters. 

Thanks for your help!

**Comment by lavrton** [comment]
Just published `vue-konva@2.1.4`. Wrong tag detection should be better. @greglaw  can you try it?

**Comment by greglaw** [comment]
That seems to have fixed it - thank you! Konva is a great package by the way - I'm really enjoying using it.

**Comment by lavrton** [comment]
👍
