### ISSUE TITLE
transform v-text wrap question

### ISSUE THREAD

**Issue by xiaoksks** [konvajs/vue-konva#58]
https://codesandbox.io/s/vuekonvatemplate-o7uel

In the process of pulling left and right, the width is not enough, transform height has not increased,
fontsize becomes smaller

What am I supposed to do? help me. Thank you.

**Comment by lavrton** [comment]
You may need to reset `scaleY` too:
```javascript
transformerText() {
      const selectedNode = this.$refs.transformer
        .getStage()
        .getStage()
        .findOne("." + this.selectedShapeName);

      this.v_text[0].width = this.v_text[0].width * selectedNode.getScaleX();

      selectedNode.scaleX(1);
      selectedNode.scaleY(1);
}
```

https://codesandbox.io/s/vuekonvatemplate-d8406
