### ISSUE TITLE
v-stage broken

### ISSUE THREAD

**Issue by repetier** [konvajs/vue-konva#59]
I use vue-konva inside a component that I have several times on a webpage so I have multipe v-stage components. Only one of them gets rendered while others trigger an error because in 
`this._konvaNode.container(this.$el);`
The old fake container gets removed. So first component succeeds as it owns the fake container. The following fail because parent does not exist any more:-(

Changing created in Stage.js to
```
  created: function created() {
    this._konvaNode = new window.Konva.Stage({
      width: this.config.width,
      height: this.config.height,
      container: document.createElement('div')
    });
  },
```

made it work again since now every element has it's own parent. Up to version 2.0.4 it worked perfectly, but the introduction of fakeContainer broke it.

Would be great if you can modify that for future version so I can update to newer versions.

**Comment by lavrton** [comment]
Fixed and published as a new version. Thanks for the report.

Demo for the working code: https://codesandbox.io/s/vuekonvatemplate-sxkfs
