### ISSUE TITLE
v-for with rect and text. It does work, but also creates a bunch of divs

### ISSUE THREAD

**Issue by L-K-Mist** [konvajs/vue-konva#60]
A strange bug.

![Screenshot_2019-06-11_10-38-43](https://user-images.githubusercontent.com/22072669/59262427-76794c80-8c3f-11e9-9bd1-a68f76c32a2e.png)
See, it works well, but: Scrolling further down the page, each repeated item (that should stay in the canvas) are instead given their own divs.

![Screenshot_2019-06-11_10-53-46](https://user-images.githubusercontent.com/22072669/59262533-acb6cc00-8c3f-11e9-8207-3619961d5b47.png)

Have you seen something like this before? 
Know what to do?

**Comment by lavrton** [comment]
What version of `vue-konva` you are using? There was a bug on one version. But it should work ok in the last version. Can you try it?

**Comment by L-K-Mist** [comment]
It's version 2.0.6 <-- guessing that's the latest yeah?

**Comment by lavrton** [comment]
Can you create a small demo with codesanbox? I tried this https://codesandbox.io/s/vue-konva-template-60sxk and it works ok.

**Comment by L-K-Mist** [comment]
Okay cool, forked your example and gonna add what I've got to see... .   While I'm at it though, is there anything you'd suggest I take a closer look at that might be causing it? 

Like thinking back to the bug that was in the earlier versions?

**Comment by L-K-Mist** [comment]
Hi Anton, I'm having a hard time replicating the problem on a smaller sandbox. The problem seems to be related to the complexity of the real app.   Might there be a clash somewhow with vuetify?

What I have noticed is that the div containing all the other divs equates to the v-layer in my code. As shown by ``` name="boxes" ```
![name is boxes](https://user-images.githubusercontent.com/22072669/59427464-00115180-8ddb-11e9-8e46-8d709231c095.png)

Might I add you to the private github repository, and send you the api key?

Or else do you think I should try using Konva direct without vue-konva?

Or is there perhaps a (hacky) way for me to delete all those divs after they appear?

I'm stumped.

**Comment by lavrton** [comment]
As workaround you may try to use `Konva` directly. But it still be very good to find underlying issues.

Do you use any live-reload methods? Do you have the issue on the production build?

**Comment by L-K-Mist** [comment]
Yes, same issue on the test-production build. https://vueocr.firebaseapp.com/  <-- console.logs still switched on.      [prayer for safety]   ;)

Using the standard vue live-reloading, yes.

Adding you to the codebase.  Most of the action is in src/components/WorkerHome/WorkerDoc.vue and the related vuex module is at src/store/modules/workerOCR.js

**Comment by lavrton** [comment]
@L-K-Mist I don't see the issue now. Did you find the solution?

**Comment by L-K-Mist** [comment]
I went with straight Konva, and its working well now. I may be wrong, but it feels like working within vue and its reactivity engine can get slow when you're dealing with like 200 rectangles and equal number of texts. 

Although it's quite snappy when I keep most variables outside of vue's data/computed properties unless they are essential to the rest of the app-state. 

 This is more guessing and gut-feeling. Maybe you have more direct insight?

**Comment by lavrton** [comment]
You are right, using Konva directly (or even native 2d canvas API) can be faster. For now, I will close the issue but will try to investigate it more. If anyone has more info about the bug, just add a comment.
