### ISSUE TITLE
How to combine both event mousedown and touchstart together?

### ISSUE THREAD

**Issue by CuongStf** [konvajs/vue-konva#62]

**Comment by lavrton** [comment]
What did you try?

**Comment by CuongStf** [comment]
can you help me?
How to prevent change size of border when i tried change transformer wrapper my shape?
@lavrton 
<img width="1016" alt="Screen Shot 2019-06-20 at 7 33 54 AM" src="https://user-images.githubusercontent.com/33604446/59810126-013c0480-932e-11e9-847c-0513f2cd26f9.png">

**Comment by lavrton** [comment]
You can use a combination of `ignoreStroke` for `Konva.Transformer` and `strokeScaleEnabled` of any `Konva.Shape`. Or just reset `scaleX` and `scaleY` and apply new `width` and `height` on each `transform` event.
