### ISSUE TITLE
When save stage to image, i could save shape, text, line, but the free drawing in layer can't save ? 

### ISSUE THREAD

**Issue by CuongStf** [konvajs/vue-konva#63]
my demo: [https://codesandbox.io/s/vue-konva-template-hcs4r](url)
I use batchDraw in layer but i can't draw, hide it,  drawing fine.

**Comment by lavrton** [comment]
The stage will draw all internal nodes into the canvas before exporting to base64.  Your manual drawing are not represented inside internal nodes, so you don't see it in export. To fix the issue you need to create an offscreen canvas with `document.createElement('canvas') and then use it for `<v-image />` element. Then draw your lines on that canvas.
