### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by YiiGuxing** [konvajs/vue-konva#64]
TypeError: Cannot read property 'add' of undefined
at VueComponent.mounted (...\node_modules\vue-konva\umd\vue-konva.js:370:23)

**Comment by Botz** [comment]
Can you please provide more infos? Or better some example code?

**Comment by YiiGuxing** [comment]
It only happens in my project, I can't reproduce it in other projects, it's weird.

**Comment by lvbirui** [comment]
i have the same problem. do you overcome it?

**Comment by rubennaatje** [comment]
Yeah me too @lvbirui 

I only have it in an electron-nuxt project, a normal nuxt project is fine. Even when it's exactly the same code.  So it I thought it had to be the whitelistedModule problem, but I tried that in a million ways.

Weird thing is that it seems to work except that the getParentNode goes all the way till root until it returns {};

`_ref.mounted = function mounted() {
    var parentVueInstance = findParentKonva(this);
    var parentKonvaNode = parentVueInstance._konvaNode;
    parentKonvaNode.add(this._konvaNode);
    updatePicture(this._konvaNode);
  }`

`function findParentKonva(instance) {
  function re(instance) {
    if (instance._konvaNode) {
      return instance;
    }
    if (instance.$parent) {
      return re(instance.$parent);
    }
    return {}; // this is what it returns.
  }
  return re(instance.$parent) // when I debug it will do this once and then it will do the right way, but the second time it tries to go to parent all the way until root.
}`

**Comment by rubennaatje** [comment]
update: turns out I needed to try it in a million and one ways.
in _renderer/nuxt.config.js_
``` json
  build: {
    extend (config, ctx) {
      config.externals = [ {
        whitelist: ['vue-konva', 'konva', 'vue']
      }]
    }
  }
```
This solved the issue. @lvbirui

**Comment by mhodge** [comment]
@rubennaatje  I am having the exact same issue with clean Laravel Nova install where I get the error TypeError: Cannot read property 'add' of undefined, does you or anyone else perhapse know how to perform a whitelist in Laravel Nova as I see that was the suggested solution for the vue-konva being inside the electron-nuxt project?

<pre>
import VueKonva from 'vue-konva'
Nova.booting((Vue, router, store) => {
  Vue.use(VueKonva)
  router.addRoutes([
    {
      name: 'my-tool',
      path: '/my-tool',
      component: require('./components/Tool'),
    },
  ])
})
</pre>

Then when visiting my tool in Nova I get the error in these lines
<pre>
_ref.mounted = function mounted() {
    var parentVueInstance = findParentKonva(this);
    var parentKonvaNode = parentVueInstance._konvaNode;
    parentKonvaNode.add(this._konvaNode);
    updatePicture(this._konvaNode);
  }
</pre>
