### ISSUE TITLE
How can we use v-label?

### ISSUE THREAD

**Issue by kushalbacancy** [konvajs/vue-konva#65]
I want to use the `v-label`, But I don't have an idea that what will the config params, Can you please give some details about `v-label`.
I ask this question and @lavrton  suggest me to use `label`.

https://github.com/konvajs/konva/issues/684#issue-465596181

Guys Please help me out. 
@freeqaz  @rafaesc @Botz @Ldoppea @MKRazz

**Comment by Botz** [comment]
@kushalbacancy 
I made a vue-konva demo for this https://konvajs.org/docs/shapes/Label.html, but only for the black tooltip.
https://codesandbox.io/s/9j1zp

I hope this will help you.

**Comment by kushalbacancy** [comment]
@Botz  Thank you so much. It's will work for me.

**Comment by Botz** [comment]
What do you mean? Like an input field you click on the text and you can change it? Or from outside the canvas?

**Comment by lavrton** [comment]
@kushalbacancy that is not so simple. Here is the demo with pure `Konva`.
https://konvajs.org/docs/sandbox/Editable_Text.html

You just need to convert it into vue approaches.

**Comment by kushalbacancy** [comment]
@lavrton I got it 

https://codesandbox.io/s/vue-konva-template-3rjz3
