### ISSUE TITLE
double tap issue

### ISSUE THREAD

**Issue by rawnanoob** [konvajs/vue-konva#67]
See https://github.com/konvajs/konva/pull/253

**Comment by lavrton** [comment]
What is the issue here?

**Comment by rawnanoob** [comment]
If you have multiple shapes on a stage and the first target of your first click/tap is different than your second. Then the second click registers as if you clicked the second target twice.

**Comment by lavrton** [comment]
Can you make a demo? If it was fixed in `konva` it should be fixed in `vue-konva` too, if you are using updated `konva` version.

**Comment by rawnanoob** [comment]
Actually it's when you double tap.
I'm using ^2.0.6. https://codepen.io/rawnanoob/pen/BXBVQY

**Comment by lavrton** [comment]
Fixed with the new version of `konva@3.4.1`.

Demo: https://codepen.io/lavrton/pen/NQWKbM
