### ISSUE TITLE
How can we update Dimensions / Position in Data property

### ISSUE THREAD

**Issue by kushalbacancy** [konvajs/vue-konva#69]
@lavrton  @Ldoppea  @Botz  @freeqaz Thank you guys for such a useful plugin,
Actually, I am having a problem. 
I need to save the JSON of `stage` but in that, if some of my element move to another place by drag and drop. then it dimensional (position/ x and y) won't be updating the original Data object.

Below is my Demo URL
https://codesandbox.io/s/vue-template-w57iz

**Comment by lavrton** [comment]
So just update values in `data` on `dragmove` or `dragend` events.

**Comment by kushalbacancy** [comment]
My issue to get the element index for Data, I didn't get the key. @lavrton

**Comment by lavrton** [comment]
You can save index into a node or use some id for it, then in `dragend` you can do this:

```javascript
handleDragEnd(e) {
   // get some information from Konva node
   const id = e.target.id();

   // find item in the data
   const item = this.data.items.find(i => i.id === id);

   // save to data
   item.x = e.target.x();
   item.y = e.target.y();
}
```

**Comment by kushalbacancy** [comment]
@lavrton  have you check my Demo URL, that the way I am handling, So is there any way to improve my existing code or where I need to put the Id?

**Comment by lavrton** [comment]
The demo is too large and shows nothing for me. Create a small one and play with it do understand the solution.

**Comment by kushalbacancy** [comment]
@lavrton 
Okay Now, I just remove the extra code from that Demo.
Some useful functions:- 
`handleDragend`, `addImageIcon`, `addSides` .

when you click on given Icon and text, it will appear in canvas and give you the ability to drag and move. 
So on that time, I am calling `handleDragend` function to update the dimension

**Comment by lavrton** [comment]
Looks like it is not updated.

**Comment by kushalbacancy** [comment]
Hello @lavrton ,
I fixed at my end.
https://codesandbox.io/s/vue-template-w57iz
