### ISSUE TITLE
How to event.cancelBubble?

### ISSUE THREAD

**Issue by DenniLa2** [konvajs/vue-konva#7]
Hello!
Thanks for library!

My code looks like this:
```
<v-layer
  ref="layer"
  @dragend="k_layer_onDragEnd"
>
<v-circle
  v-for="(p, i) in kPoints"
  :key="`point${i}`"
  :config="p"
  :ref="`point${p.name}`"
  @dragend="k_point_onDragEnd"
></v-circle>
</v-layer>

<script>
  k_layer_onDragEnd(layer) {
        console.log(' ---> k_layer_onDragEnd');
  },
  k_point_onDragEnd(point, e) {
        e.evt.cancelBubble = true;
        // more...
  },
</script>
```

And event pops up =(

How to set cancelBubble to true?

**Comment by Ldoppea** [comment]
Hi,

`e` is already the event, so `e.cancelBubble = true;` should do the trick (just remove `.evt`)

**Comment by muuma** [comment]
Hello!
Thanks for library!

My code looks like this:


         <v-group 
            ref="group" 
            :config="{
            x: config.x,
            y: config.y,
            width: config.width,
            height: config.height,
            image: config.img,
            draggable: config.draggable,
            if(config.type === 'rect') {                      
                ctx.rect(0, 0, config.width, config.height)
            }
            }"
            @dragstart="dragStart"
            @dragmove="dragMove"
            @dragend="dragEnd"/>

        <v-image 
            ref="image" 
            :config="{
            width: config.width,
            height: config.height,
            image: config.img,
            draggable: !config.draggable
            }"
            @dragstart="dragStartImage"
            @dragmove="dragMoveImage"
            @dragend="dragEndImage"/>
            
    </v-group>


script: 


        dragStart () {
            console.log('group')
        },
        dragStartImage (e) {
            console.log('image')
            e.cancelBubble = true
        }


And event pops up =(

How to set cancelBubble to true?

**Comment by Ldoppea** [comment]
Hi,

This is because the first arg for dragStart is the dragged element. Regarding the event, you should get it fromthe 2nd argument.

Try this instead : 

```
dragStartImage (element, e) {
   console.log('image')
   e.cancelBubble = true // or maybe e.evt.cancelBubble = true
}
```

**Comment by muuma** [comment]
enen, thank you very much
