### ISSUE TITLE
Performance issues with video

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [konvajs/vue-konva#72]
Based on the vanilla JS example on how to include a video on the canvas (https://konvajs.org/docs/sandbox/Video_On_Canvas.html) I went ahead and made a test case based on the Vue Konva library: https://codesandbox.io/s/vue-konva-template-0v4lz

However, the performance is clearly slower on the Vue Konva version, and I couldn’t figure out why.

**Comment by lavrton** [comment]
I don't see any performance issues. Looks like there are some issues with the video itself and its loading speed. It works just fine with another video:

https://codesandbox.io/s/vue-konva-video-example-1plfi

**Comment by dsdsdsdsdsds** [comment]
OK, just realized it seems only Google Chrome (I’m on Mac version 76) has performance issues. I tried loading the video locally, but no improvements. Running the example in Safari or Firefox shows no severe problems. Can you confirm that?

**Comment by lavrton** [comment]
Yeah, it works ok for me in Safari. Probably it is the issue with Chrome + video codec.
