### ISSUE TITLE
Cache components

### ISSUE THREAD

**Issue by sc-laurence** [konvajs/vue-konva#73]
Hi guys,

Thanks for making Konva and porting it to Vue.

Just wondering if I am to use the v-for same component for vue-konva, how do I cache the component for reuse or does it take care of it already?

Thanks again guys.

**Comment by lavrton** [comment]
What do you mean by cache for reuse?

**Comment by sc-laurence** [comment]
`<template>
    <v-rect
        :config="rectConfig"
    >
    </v-rect>
</template>
<script>
export default {
    computed: {
        rectConfig() {
            return {
                x: 20,
                y: 20,
                width: 100,
                height: 50,
                fill: 'green',
                stroke: 'black',
                strokeWidth: 4
            };
        }
    },
}
</script>
<style lang="css" scoped>
    
</style>`

For exanple, if I have the above as a singular component <standard-rect/> and calling the looping it with v-for loop. Would I need to cache the component in the mounted function for performance benifit? If so how do I make sure its only cached once?

Sorry if this is a stupid question, just started using Konva so do apologise in advance

**Comment by lavrton** [comment]
If you mean Konva's caching https://konvajs.org/docs/performance/Shape_Caching.html you can do that at any `vue` lifecycle methods such as `mounted` or `updated`.

For exactly this shape from your example, it doesn't' make much sense to cache it. The shape is simple, so you will not have perf boost.

**Comment by sc-laurence** [comment]
Cool thanks for the quick response. Thanks again for everything.
