### ISSUE TITLE
group element

### ISSUE THREAD

**Issue by Franz0410** [konvajs/vue-konva#76]
How can i create a group with transformer and draggable with a shape and a text inside of it with v-for

**Comment by Franz0410** [comment]
i tried a v-for of the v-group and inside i put the shape, for example v-rect, and a v-text, but the text is not dreggable and the tranformer is in another position of the shape

**Comment by lavrton** [comment]
Can you make a demo with https://codesandbox.io?

**Comment by lavrton** [comment]
Closing the issue for now, as not enough information. If you have a demo or a code sample - please share.
