### ISSUE TITLE
Style cursor for a layer

### ISSUE THREAD

**Issue by mtriff** [konvajs/vue-konva#78]
How can we style the cursor based on the items that have been drawn in a `v-layer` or `v-stage`?

I've seen the example for [Change Mouse Cursor Style](https://konvajs.org/docs/styling/Mouse_Cursor.html), but I don't see a way to pass a cursor value to the Vue components. Wrapping the stage in a div and styling the div does not work since the rendered canvas component overrides the cursor value.

**Comment by lavrton** [comment]
What exactly did you try?

Here is my solution:
```javascript
<template>
  <v-text
    :config="{text: 'Hover text to change cursor', fontSize: 15, x: 50, y: 50 }"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  />
</template>

<script>
export default {
  props: ["cursor"],
  methods: {
    handleMouseEnter(e) {
      const stage = e.target.getStage();
      stage.container().style.cursor = this.cursor;
    },
    handleMouseLeave(e) {
      const stage = e.target.getStage();
      stage.container().style.cursor = "default";
    }
  }
};
</script>
```

Then use:

```javascript
<v-stage ref="stage" :config="stageSize">
    <v-layer>
      <v-cursor cursor="pointer"/>
    </v-layer>
    <v-layer ref="dragLayer"></v-layer>
  </v-stage>
```

Demo: https://codesandbox.io/s/vue-konva-cursor-change-demo-78538

**Comment by mtriff** [comment]
Thanks for the solution, I wasn't sure how to get the JS representation of the stage in vue-konva (I did not know about the `e.target.getStage()` method). 

I also just realized I have a conflicting CSS rule that was overriding the cursor style of the canvas when I set the cursor style on the `div`. 

Thanks for all the work you put into Konva!
