### ISSUE TITLE
Click/Mousedown trigger a dragend event

### ISSUE THREAD

**Issue by Mozfe** [konvajs/vue-konva#79]
My vue-konva version is 2.0.9.
I have a `v-group` which listen both of mouse and drag events. When i click on the group, the dragend event will be triggered as well. Is there a way to solve this problem？
```
<v-group :config="groupConfig"
    @dragend="dragEnd"
    @mousedown="handleMouseDown"
 >
```
By the way, the changelog of konvajs shows they `"Fix dragend event on click"` at version 4.0.8 , don't know if it's the same problem or not
https://github.com/konvajs/konva/blob/master/CHANGELOG.md#408----2019-09-05

**Comment by lavrton** [comment]
Yeah. It should be fixed. Try to update to the latest version of `konva`.

`npm install konva@latest`

**Comment by lavrton** [comment]
Let me know if it still not works for you.

**Comment by Mozfe** [comment]
It works. Thank you:)
