### ISSUE TITLE
Make componentPrefix configurable

### ISSUE THREAD

**Issue by StevenWarren** [konvajs/vue-konva#80]
I'm attempting to use VueKonva in an existing project that uses the Vuetify library. Every thing seems to work well so far, except for V-Label. Vuetify has a component named V-Label as well and it is taking precedent. Looking at the code source it appears that in utils.js componentPrefix is set as a constant. Is there anyway to make that configurable at registration? I tried excluding the Vuetify component using their a la carte registration but V-Label is a nested dependency in their form components which we are utilizing heavily so of course everything blows up.

**Comment by lavrton** [comment]
Hmmm. Currently, I am not sure how to organize it better.

**Comment by StevenWarren** [comment]
I agree, was looking at it last night and couldn't find an easy solution. So I just pulled the JS directly and made the change to move forward. It works, but is very sub-optimal. I will take another stab at it later.
