### ISSUE TITLE
Problems encountered in dragging changes in element hierarchy

### ISSUE THREAD

**Issue by wzanbaichi** [konvajs/vue-konva#81]
hello,
I got an issue.

I use the example of the official website to demonstrate.

When I drag some stars and cause their hierarchical changes, but when I press the button to modify the data and cause the view to update, the hierarchy of stars is restored again. This is not what I want to see. I hope they can keep the hierarchy when dragging.

My English is not good. I hope you can understand it. Thank you.

The code is as follows:

```
<template>
  <div>
    <p>{{testText}}</p>
    <button @click="test">sadsa</button>
    <v-stage
      ref="stage"
      :config="configKonva"
      @dragstart="handleDragstart"
      @dragend="handleDragend"
    >
      <v-layer ref="layer">
        <v-star v-for="item in list" :key="item.id" :config="item"></v-star>
      </v-layer>
      <v-layer ref="dragLayer"></v-layer>
    </v-stage>
  </div>
</template>

<script>
const width = window.innerWidth;
const height = window.innerHeight;
let vm = {};
export default {
  data() {
    return {
      list: [],
      configKonva: {
        width: width,
        height: height
      },
      testText: "sss"
    };
  },
  methods: {
    test() {
      this.testText = Math.random();
    },
    handleDragstart(e) {
      const shape = e.target;
      const dragLayer = vm.$refs.dragLayer.getNode();
      const stage = vm.$refs.stage.getNode();
      // moving to another layer will improve dragging performance
      shape.moveTo(dragLayer);
      stage.draw();
      shape.setAttrs({
        shadowOffsetX: 15,
        shadowOffsetY: 15,
        scaleX: shape.getAttr("startScale") * 1.2,
        scaleY: shape.getAttr("startScale") * 1.2
      });
    },
    handleDragend(e) {
      const shape = e.target;
      const layer = vm.$refs.layer.getNode();
      const stage = vm.$refs.stage.getNode();
      shape.moveTo(layer);
      stage.draw();
      shape.to({
        duration: 0.5,
        easing: Konva.Easings.ElasticEaseOut,
        scaleX: shape.getAttr("startScale"),
        scaleY: shape.getAttr("startScale"),
        shadowOffsetX: 5,
        shadowOffsetY: 5
      });
    }
  },
  mounted() {
    vm = this;
    for (let n = 0; n < 30; n++) {
      const scale = Math.random();
      const stage = vm.$refs.stage.getStage();
      vm.list.push({
        x: Math.random() * stage.width(),
        y: Math.random() * stage.height(),
        rotation: Math.random() * 180,
        numPoints: 5,
        innerRadius: 30,
        outerRadius: 50,
        fill: "#89b717",
        opacity: 0.8,
        draggable: true,
        scaleX: scale,
        scaleY: scale,
        shadowColor: "black",
        shadowBlur: 10,
        shadowOffsetX: 5,
        shadowOffsetY: 5,
        shadowOpacity: 0.6,
        startScale: scale
      });
    }
  }
};
</script>
```

**Comment by lavrton** [comment]
Hey, I updated the demo on the site, so it looks more in a "vue-way". What is your issue? You don't want to move elements to the top on drag event? Or you don't want to move it back on text changes?

If you have a second issue, take a look into updated example:https://codesandbox.io/s/github/konvajs/site/tree/master/vue-demos/basic_demo?from-embed

**Comment by wzanbaichi** [comment]
@lavrton 

I mean I don't want to move it back on text changes,

**Comment by wzanbaichi** [comment]
I hope that when I click on the star, it moves to the top and does not change back when the text changes.

**Comment by lavrton** [comment]
Yeah. So with the updated demo, it will work just fine. The key here is to save the order of elements inside the `data` of a component. In previous version of the demo there was some a movement of nodes with `shape.moveTo(dragLayer);`. But that practice is not really good.

**Comment by wzanbaichi** [comment]
do you mean by saving the element's `sortNumber` in the data and then rendering the elements in the order of `sortNumber`?

**Comment by wzanbaichi** [comment]
Thank you, I already understand what you mean.
But I found some problems on your demo that the official website example is not working properly.


Here is your code
`
 handleDragstart(e) {
      // save drag element:
      this.dragItemId = e.target.id();
      // move current element to the top:
      const item = this.items.find((i => i.id === this.dragItemId));
      const index = this.items.indexOf(item);
      this.items.splice(index, 1);
      this.items.push(item);
    },
`
The following is my revised
·
handleDragstart(e) {
      // save drag element:
      this.dragItemId = e.target.id();
      // move current element to the top:
      const item = this.list.find((i => i.id === this.dragItemId));
      const index = this.list.indexOf(item);
      this.list.splice(index, 1);
      this.list.push(item);
    },
·
