### ISSUE TITLE
Not working install to Nuxt.js with npm

### ISSUE THREAD

**Issue by Mike-Kharkov** [konvajs/vue-konva#82]
Hi!
I try to install vue-konva to my app and I got trouble:
[http://joxi.ru/12MgEPYhlaZxZr](http://joxi.ru/12MgEPYhlaZxZr)
I did the next steps:
1) npm install vue-konva konva --save
2) [http://joxi.ru/KAg5e6oHElQJNm](http://joxi.ru/KAg5e6oHElQJNm)
3) [http://joxi.ru/DrlK6ZoCVNLOqA](http://joxi.ru/DrlK6ZoCVNLOqA)

What did I do wrong?

**Comment by lavrton** [comment]
There is nothing wrong with your steps. Looks like our build is not good for nodejs env (I guess that is where nuxt.js is running). Right now I am not sure how to resolve this issue. Need to think about it.

**Comment by Mike-Kharkov** [comment]
How much time do you need?

**Comment by lavrton** [comment]
Just published `vue-konva@2.0.11` you can update and try it.

**Comment by Mike-Kharkov** [comment]
Error is disappeared.
