### ISSUE TITLE
Window is not defined.

### ISSUE THREAD

**Issue by Mike-Kharkov** [konvajs/vue-konva#83]
Hi!
I have this code:(nuxt.js 2.9.2)
[http://joxi.ru/E2p3KO1H7ZwZ1m](http://joxi.ru/E2p3KO1H7ZwZ1m)
And I have this error:
[http://joxi.ru/KAxpx8oHZkpd3A](http://joxi.ru/KAxpx8oHZkpd3A)
What did I do wrong?

**Comment by tomavc** [comment]
I ended up having to do this in my main.js file, just before my new Vue( stuff.

import VueKonva from 'vue-konva'
Vue.use(VueKonva)

**Comment by lavrton** [comment]
There is not enough information about the issue. I guess it is a server-side rendering problem.

I am closing the issue for now. If someone still has the problems, please make a small reproducible repo.
