### ISSUE TITLE
Components logged during install phase

### ISSUE THREAD

**Issue by alextarrell** [konvajs/vue-konva#89]
As of version 2.1.0, a console log is printing out the name of every component whenever the plugin is initialized. This is undesirable.
https://github.com/konvajs/vue-konva/blob/43642e819e92a22646304db796cef4e5ae05b9c7/src/index.js#L51

Console output:
> vStage
vLayer
vFastLayer
vGroup
vLabel
vRect
... etc

**Comment by lavrton** [comment]
Thanks for the report. Fixed with `vue-konva@2.1.1`.
