### ISSUE TITLE
Usage with NuxtJS?

### ISSUE THREAD

**Issue by speed676** [konvajs/vue-konva#9]
Hi everyone,

Sorry if this is the wrong place as it is not an issue. Is there a better way to ask for support?

I would like to use vue-konva in addition to NuxtJS, but the main problem is that it does not paint. 

I'm using:
* nuxt: "1.4.0",
* vue-konva: "1.0.5",
* vue: "2.5.13"

I have to component "konva.vue" with this code:

```
<template>
<div>
  <v-stage ref="stage" :config="configKonva">
    <v-layer ref="layer">
      <v-circle :config="configCircle"></v-circle>
    </v-layer>
  </v-stage>
</div>
</template>

<script>
export default {
  data: () => ({
    configKonva: {
      width: 400,
      height: 200
    },
    configCircle: {
      x: 200,
      y: 100,
      radius: 40,
      fill: 'red',
      stroke: 'black',
      strokeWidth: 4
    }
  })
}
</script>
```

When I use the `<konva></konva>` component. Vue-konva creates the canvas html element with correct properties.

Generate:
```
<div class="konvajs-content" role="presentation" style="position: relative; width: 400px; height: 200px;">
    <canvas width="400" height="200" style="padding: 0px; margin: 0px; border: 0px; background: transparent; position: absolute; top: 0px; left: 0px; width: 400px; height: 200px;"></canvas>
</div>
```
And here is the problem. Vue-konva not printing:
![image](https://user-images.githubusercontent.com/3138061/38246868-70236336-3743-11e8-9506-df52865cce35.png)

I do not know what is happening :(. 

What are your thoughts about this?

**Comment by Ldoppea** [comment]
Do you have any error printed on the console?

Not sure if related, but did you try this : https://github.com/rafaesc/vue-konva/issues/3#issuecomment-362099662 ?

**Comment by speed676** [comment]
Hi,

The result of the solution in relation to your link.

You have to apply the solution explained here https://github.com/nuxt/nuxt.js/issues/1142#issuecomment-317272538

Only add in your `nuxt.config.js`:

```
build: {
        extend(config) {
            config.resolve.alias['vue'] = 'vue/dist/vue.common'
        }
    }
```

Result:
![image](https://user-images.githubusercontent.com/3138061/38249302-843b40c0-374b-11e8-8f82-8be916279d36.png)

Thanks!! :)

**Comment by lavrton** [comment]
Closing is for now, as it seems the workaround works.
