### ISSUE TITLE
How to load and play multiple videos dynamically generated

### ISSUE THREAD

**Issue by Relatora** [konvajs/vue-konva#91]
Hi,
I get a JSON string that gives me the location of video assets to be rendered in real-time. Basically I loop over child video components and I have trouble getting the stage and layer because they are still undefined (to animate the video inside the child component) at the time of the child component creation. I found very few examples online all tackling only one video. If you can point me out to some working code I will be very grateful.

Thanks in advance

**Comment by Relatora** [comment]
![image](https://user-images.githubusercontent.com/50456511/70195591-1fc36b80-16d4-11ea-8b90-3b966ffd4695.png)
![image](https://user-images.githubusercontent.com/50456511/70195614-35d12c00-16d4-11ea-89bb-7fbb37d4e472.png)

**Comment by lavrton** [comment]
Do not use `span` as a child of konva nodes. It may break the flow.

I think we should add a warning of such a use case.
From the code above it is hard to understand what is not correct. What is `elm-konva-video` how it works?

**Comment by lavrton** [comment]
Closing as not enough info.
