### ISSUE TITLE
After tranformer done event

### ISSUE THREAD

**Issue by hbl-anhnt1** [konvajs/vue-konva#94]
After tranformer done, Are there any events for this?
I try to handleBoundBoxFunc but if use it, it very event when tranformer not done.
And after tranformer done, shape changed but data in config not change. How to set or update it ?

**Comment by lavrton** [comment]
There is `transformend` event.

I updated a demo here: https://konvajs.org/docs/vue/Transformer.html

**Comment by lush-99** [comment]
i found the function: e.target.getClientRect()
