### ISSUE TITLE
[Question] Can we make an enclosure interactively?

### ISSUE THREAD

**Issue by e0lithic** [konvajs/vue-konva#95]
Hi,

I am just getting my hands wet in frontend development and came across your brilliant library. However, going through the manuals I wasn't able to figure out a desired outcome. Can we interactively take inputs (on top of an image ) from user in the form of mouse events , where he/she sequentially creates an enclosure (an effect similar to the Path tool in GIMP), which we can then use to highlight that section of image using opacity in a given color (presuming it would be simply be a form of fill function)
Something similar to the following (the blue points being the users clicks ) - 
![example](https://user-images.githubusercontent.com/11680315/71775972-3ef13980-2faf-11ea-85fa-6a85f4d91b08.png)

If so any pointers for achieving the same would be greatly appreciated.

Thanks

**Comment by lavrton** [comment]
Yes, that is totally possible. I made a prototype application that works very similar to what you want.

https://lavrton.com/case-study-image-labeling-for-machine-learning/

The app is made with `react-konva`, but it can be written in `vue-konva` too.

**Comment by e0lithic** [comment]
@lavrton Thanks for the great write up. 

On a side note, I was trying to implement the above using a dynamic polygon. However, I realized that konva supports transformers for custom shapes by defining a bounding rectangle for it ([StackOverflow](https://stackoverflow.com/questions/50571367/konvajs-custom-shapes-and-transformers)) and hence modifying an existing shape becomes a little tricky. Is there any way where i can modify the dynamically created polygon coordinates ( by dragging them to new locations) as well to achieve something like the following gif - 
![path](https://user-images.githubusercontent.com/11680315/72064590-34fa6e00-3302-11ea-99de-92d5a78426c4.gif)

Thanks.

**Comment by lavrton** [comment]
Yeah, you can implement such a function. You don't need `Konva.Transformer` here. It is a custom resizing.

Take a look into this demo: https://konvajs.org/docs/sandbox/Modify_Curves_with_Anchor_Points.html
