### ISSUE TITLE
Question: Would I animate components individually or globally.

### ISSUE THREAD

**Issue by jackdt8** [konvajs/vue-konva#96]
Hello,

I am attempting to build a 2d shooting game and am running into some animation difficulties. For bullets, essentially I am pushing a bullet config state through Vuex and feeding it through an array using a component inside of it's own v-layer.

When I attempt to animate the array, only the first bullet seems to render. Any actions multiply by the length of the array, however only the first bullet is actually rendered on the canvas.

__

So I was wondering. For a game such as this which would constantly have a running animation, whether it be a player or enemy, bullets, etc.. Is it better to tie a Konva Animation instance to each component individually, or keep track of all changes globally with an Animation instance in its own layer?

**Comment by lavrton** [comment]
> When I attempt to animate the array, only the first bullet seems to render. Any actions multiply by the length of the array, however only the first bullet is actually rendered on the canvas.

Can you make a demo of that issue?

> Is it better to tie a Konva Animation instance to each component individually, or keep track of all changes globally with an Animation instance in its own layer?

In terms of performance, it will be almost the same. I terms of code complexity, I think that the first approach (with many animations) will be simpler.

**Comment by daniel-enmasse** [comment]
While making a demo of the issue on CodeSandbox, I realized my mistake. I'm new to Vue / Vuex and was setting / getting my bullets from a Vuex state, essentially re-initializing the same state object over and over instead of cloning a local copy to work with!

Rookie mistake. Anyway thanks for the performance advice. I agree, being able to debug individual animation instances would be simpler. I'll start with that.

**Comment by jackdt8** [comment]
While making a demo of the issue on CodeSandbox, I realized my mistake. I'm new to Vue / Vuex and was setting / getting my bullets from a Vuex state, essentially re-initializing the same state object over and over instead of cloning a local copy to work with!

Rookie mistake. Anyway thanks for the performance advice. I agree, being able to debug individual animation instances would be simpler. I'll start with that.
