### ISSUE TITLE
Dispatch event for <stage> element

### ISSUE THREAD

**Issue by arifhussain353** [konvajs/vue-konva#97]
I bind `@wheel` event `handleWheel` on  `<stage>`.  `handleWheel` is working on a `mouse` scroll but can't call by dispatch this event by click.

![Screenshot from 2020-01-29 13-15-24](https://user-images.githubusercontent.com/12670763/73339435-a3e03c80-429a-11ea-9b69-355b68820716.png)

Now I want to `dispatch` this event by a click but it's not working reason is no wheel event listener.

![Screenshot from 2020-01-29 13-25-32](https://user-images.githubusercontent.com/12670763/73339574-dc801600-429a-11ea-8d41-2473de34dbff.png)
My code below:-
```
<div class="test" @click="manualZoom()">trigger wheel event of stage</div>

//method 
  manualZoom() {
      const dashboardStage =this.$refs.dashboardStage // getting ref of <stage>
      console.debug(dashboardStage,"dashboardStage") 
      let centerX = dashboardStage.clientLeft + dashboardStage.clientWidth / 2
      let centerY = dashboardStage.clientTop + dashboardStage.clientHeight / 2
      const event = new WheelEvent('wheel', {clientX: centerX, clientY: centerY, deltaY: value, deltaMode: 0})
      dashboardStage.dispatchEvent(event)
     },
```
This work when i bind same way on `HTML` parent `div` element.
Am I doing anything wrong?

**Comment by lavrton** [comment]
Can you make a small demo, please?


But personally I don't think triggering events manually is the best approach. Instead, you can just  make `zoomCanvas()` and then call it from `wheel` or `click` event.
