### ISSUE TITLE
stage.destroy() not working

### ISSUE THREAD

**Issue by juakotorres** [konvajs/vue-konva#99]
Konvas does not destroy the stage while navigating with vue router.  I tried to use the beforeDestroy method to delete the stage in each navigation.

```
beforeDestroy: function () {
    this.stage.destroyChildren();
    this.stage.destroy();
}
```

**Comment by lavrton** [comment]
If you use `vue-konva` you don't need to destroy a stage.

Just don't render it in your templates.

**Comment by lavrton** [comment]
How do you see that it is not working?

**Comment by juakotorres** [comment]
The app memory usage increment on each navigation, but i found it was a strange behaviour of google chrome garbage collector. 

In my app i navigate between two routes and one of them has a konvas canvas. I tried to force the garbage collector reloading the page and solved the issue.

Navigating with vue router.

<img width="614" alt="Screen Shot 2020-02-24 at 4 45 02 PM" src="https://user-images.githubusercontent.com/18192927/75189639-5fc34900-572d-11ea-9525-1c999fccc338.png">

Using window.location.reload() to force the garbage collector. 

<img width="647" alt="Screen Shot 2020-02-24 at 5 46 19 PM" src="https://user-images.githubusercontent.com/18192927/75189767-a9139880-572d-11ea-889e-0ea9f2fe4c02.png">

**Comment by lavrton** [comment]
If forcing fixes the issue, it means something with the browser. Probably you just need to wait more for memory cleaning.
